export function chatFeatures({db,all,get,put,own,safeFile,notify,notifyAdmins,send,fail,text,now,sha,markNoticesForRoute}){
 const clientChatIds=user=>new Set(all('request',user.id).map(r=>r.id));
 const chatIds=user=>new Set(all('assignment',user.id).filter(t=>!['Cancelada','Finalizada'].includes(t.status)).map(t=>t.requestId));
 const chatOwn=(user,r)=>{if(user.role==='employee')fail(404,'Conversación no encontrada.');if(user.role==='client')own(user,r);if(user.role==='client'&&!clientChatIds(user).has(r.id))fail(403,'No podés acceder a esta conversación.');return own(user,r);};
 const chatState=user=>{const ids=chatIds(user);return {chatRequests:all('request').filter(r=>ids.has(r.id)).map(r=>({id:r.id,name:r.name,service:r.service,town:r.town})),messages:all('message').filter(m=>ids.has(m.requestId))};};
 const chatMedia=(user,p)=>{if(user.role!=='employee')return false;const ids=chatIds(user);return all('message').some(m=>ids.has(m.requestId)&&m.photos?.includes(p));};
 const messagePosition=id=>db.prepare("SELECT rowid FROM docs WHERE id=? AND kind IN ('message','clientMessage')").get(id)?.rowid||0;
 const chatReadRows=()=>db.prepare("SELECT owner,body FROM docs WHERE kind='chatRead'").all().map(row=>{try{return {owner:row.owner,...JSON.parse(row.body)}}catch{return {owner:row.owner}}});
 const clientReadRows=()=>db.prepare("SELECT owner,body FROM docs WHERE kind='clientChatRead'").all().map(row=>{try{return {owner:row.owner,...JSON.parse(row.body)}}catch{return {owner:row.owner}}});
 const registeredClient=id=>db.prepare("SELECT id,name,email,phone,town FROM users WHERE id=? AND role='client' AND active=1").get(id)||null;
 const clientMessages=clientId=>[...all('message',clientId),...all('clientMessage',clientId)].sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||String(a.id||'').localeCompare(String(b.id||'')));
 const resolveClientId=(user,value)=>{if(user.role==='client')return user.id;if(user.role!=='admin')fail(404,'Conversación no encontrada.');const clientId=text(value);if(!registeredClient(clientId))fail(404,'Cliente no encontrado.');return clientId;};
 const legacyChatSummary=user=>{const permitted=user.role==='admin'?null:user.role==='employee'?chatIds(user):clientChatIds(user),reads=new Map(all('chatRead',user.id).map(r=>[r.requestId,r.lastMessageId])),latest={},unread={},stopped=new Set(),messages=user.role==='client'?all('message',user.id):all('message');for(const m of messages){if(permitted&&!permitted.has(m.requestId))continue;latest[m.requestId]??=m.id;if(reads.get(m.requestId)===m.id)stopped.add(m.requestId);if(!stopped.has(m.requestId)&&m.senderId!==user.id)unread[m.requestId]=(unread[m.requestId]||0)+1;}const chatReadByOther={},rows=chatReadRows(),adminIds=user.role==='client'?new Set(db.prepare("SELECT id FROM users WHERE role='admin' AND active=1").all().map(r=>r.id)):null,requestsById=new Map(all('request').map(r=>[r.id,r]));for(const requestId of Object.keys(latest)){let candidates=rows.filter(r=>r.requestId===requestId&&r.owner!==user.id);if(user.role==='admin'){const request=requestsById.get(requestId);candidates=request?.userId?candidates.filter(r=>r.owner===request.userId):[];}else if(user.role==='client')candidates=candidates.filter(r=>adminIds.has(r.owner));else candidates=[];let best=null,bestPos=0;for(const marker of candidates){const pos=messagePosition(marker.lastMessageId);if(pos>bestPos){best=marker;bestPos=pos;}}if(best?.lastMessageId)chatReadByOther[requestId]=best.lastMessageId;}return {chatUnread:unread,chatLatest:latest,chatReadByOther};};
 const directChatSummary=(user,legacy)=>{
  if(!['admin','client'].includes(user.role))return {clientChatUnread:{},clientChatLatest:{},clientChatReadByOther:{}};
  const clientIds=user.role==='client'?[user.id]:db.prepare("SELECT id FROM users WHERE role='client' AND active=1").all().map(row=>row.id),reads=new Map(all('clientChatRead',user.id).map(marker=>[marker.clientId,marker.lastMessageId])),latest={},unread={},readByOther={},rows=clientReadRows(),adminIds=user.role==='client'?new Set(db.prepare("SELECT id FROM users WHERE role='admin' AND active=1").all().map(row=>row.id)):null;
  for(const clientId of clientIds){
   const messages=clientMessages(clientId);if(!messages.length)continue;const last=messages[messages.length-1];latest[clientId]=last.id;const marker=reads.get(clientId);
   if(marker){const markerIndex=messages.findIndex(message=>message.id===marker);for(const message of messages.slice(markerIndex+1))if(message.senderId!==user.id)unread[clientId]=(unread[clientId]||0)+1;}
   else{const requestIds=all('request',clientId).map(request=>request.id);unread[clientId]=requestIds.reduce((sum,requestId)=>sum+(legacy.chatUnread?.[requestId]||0),0)+all('clientMessage',clientId).filter(message=>message.senderId!==user.id).length;if(!unread[clientId])delete unread[clientId];}
   let candidates=rows.filter(row=>row.clientId===clientId&&row.owner!==user.id);if(user.role==='admin')candidates=candidates.filter(row=>row.owner===clientId);else candidates=candidates.filter(row=>adminIds.has(row.owner));let best=null,bestPos=0;for(const candidate of candidates){const pos=messagePosition(candidate.lastMessageId);if(pos>bestPos){best=candidate;bestPos=pos;}}
   if(best?.lastMessageId)readByOther[clientId]=best.lastMessageId;else{const requestIds=new Set(all('request',clientId).map(request=>request.id));let legacyBest='',legacyBestPos=0;for(const [requestId,lastMessageId] of Object.entries(legacy.chatReadByOther||{})){if(!requestIds.has(requestId))continue;const pos=messagePosition(lastMessageId);if(pos>legacyBestPos){legacyBest=lastMessageId;legacyBestPos=pos;}}if(legacyBest)readByOther[clientId]=legacyBest;}
  }
  return {clientChatUnread:unread,clientChatLatest:latest,clientChatReadByOther:readByOther};
 };
 const chatSummary=user=>{const legacy=legacyChatSummary(user),direct=directChatSummary(user,legacy);if(user.role==='client'){const marker=all('clientChatRead',user.id).find(item=>item.clientId===user.id)?.lastMessageId||'',markerPos=messagePosition(marker),directUnread=all('clientMessage',user.id).filter(message=>message.senderId!==user.id&&messagePosition(message.id)>markerPos).length;if(directUnread)legacy.chatUnread.__client=directUnread;else delete legacy.chatUnread.__client;}return {...legacy,...direct};};
 const staffMessages=user=>user.role==='admin'?all('staffMessage'):user.role==='employee'?all('staffMessage',user.id):[];
 const staffUnread=user=>{if(user.role!=='employee')return 0;const marker=all('staffRead',user.id)[0]?.date||'';return staffMessages(user).filter(message=>message.senderRole==='admin'&&message.date>marker).length;};
 const staffReadByEmployee=()=>Object.fromEntries(all('staffRead').filter(r=>r.userId&&r.date).map(r=>[r.userId,r.date]));
 const staffReadByAdmin=employeeId=>all('staffAdminRead').filter(r=>r.employeeId===employeeId&&r.date).sort((a,b)=>b.date.localeCompare(a.date))[0]?.date||'';
 const routeBeforeBody=({p,method,user,url,res})=>{if(method==='GET'&&/^\/api\/requests\/[^/]+\/messages$/.test(p)){const request=chatOwn(user,get('request',p.split('/')[3]));const messages=all('message',request.userId).filter(m=>m.requestId===request.id).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));const after=url.searchParams.get('after'),index=messages.findIndex(m=>m.id===after);send(res,200,{...chatSummary(user),messages:index>=0?messages.filter(m=>m.id!==after&&m.date>=messages[index].date):messages});return true;}return false;};
 const routeAfterBody=({p,method,b,user,url,res})=>{
  if(p==='/api/client-chat/messages'&&method==='POST'){const clientId=resolveClientId(user,b.clientId);if(!/^[\w-]{8,100}$/.test(b.idempotencyKey||''))fail(400,'Referencia inválida.');const message=text(b.text,4000),files=Array.isArray(b.photos)?b.photos:[];if(files.length>4||(!message&&!files.length))fail(400,'Escribí un mensaje o adjuntá hasta cuatro fotos.');const photos=files.map(key=>safeFile(user,key,'image/')),messageId='client-msg-'+sha(user.id+':'+b.idempotencyKey),old=all('clientMessage',clientId).find(item=>item.id===messageId);if(old){send(res,200,old);return true;}const result=put('clientMessage',clientId,{id:messageId,clientId,userId:clientId,senderId:user.id,senderName:user.name,senderRole:user.role,text:message,photos,date:now()});if(user.role==='client')notifyAdmins('Nuevo mensaje',user.name+' te escribió.','/#chat-user/'+clientId,'important');else notify(clientId,'AMC te escribió','Tenés un mensaje nuevo.','/#chat-user/'+clientId,'important');send(res,201,result);return true;}
  if(p==='/api/client-chat/read'&&method==='POST'){const clientId=resolveClientId(user,b.clientId),messages=clientMessages(clientId),message=messages.find(item=>item.id===b.lastMessageId);if(!message)fail(400,'Mensaje inválido.');const key='client-read-'+sha(user.id+':'+clientId),previous=all('clientChatRead',user.id).find(item=>item.id===key);if(!previous||messagePosition(message.id)>messagePosition(previous.lastMessageId))put('clientChatRead',user.id,{id:key,clientId,lastMessageId:message.id,readerId:user.id,readerRole:user.role,date:now()});for(const request of all('request',clientId)){const requestMessages=all('message',clientId).filter(item=>item.requestId===request.id).sort((a,b)=>messagePosition(a.id)-messagePosition(b.id)),last=requestMessages.at(-1);if(!last)continue;const legacyKey='read-'+sha(user.id+':'+request.id),legacyPrevious=all('chatRead',user.id).find(item=>item.id===legacyKey);if(!legacyPrevious||messagePosition(last.id)>messagePosition(legacyPrevious.lastMessageId))put('chatRead',user.id,{id:legacyKey,requestId:request.id,lastMessageId:last.id,readerId:user.id,readerRole:user.role,date:now()});}const noticeIds=markNoticesForRoute(user,'/#chat-user/'+clientId);send(res,200,{ok:true,noticeIds});return true;}
  if(method==='POST'&&/^\/api\/requests\/[^/]+\/messages\/read$/.test(p)){const r=chatOwn(user,get('request',p.split('/')[3])),message=get('message',b.lastMessageId);if(message.requestId!==r.id)fail(400,'Mensaje inválido.');const key='read-'+sha(user.id+':'+r.id),previous=all('chatRead',user.id).find(x=>x.id===key);if(!previous||messagePosition(message.id)>messagePosition(previous.lastMessageId))put('chatRead',user.id,{id:key,requestId:r.id,lastMessageId:message.id,readerId:user.id,readerRole:user.role,date:now()});const noticeIds=markNoticesForRoute(user,user.role==='admin'?'/#chat-admin/'+r.id:'/#chat/'+r.id);send(res,200,{ok:true,noticeIds});return true;}
  if(p==='/api/staff-chat/messages'&&method==='GET'){if(!['admin','employee'].includes(user.role))fail(404,'No encontrado.');const employeeId=user.role==='employee'?user.id:text(url.searchParams.get('employeeId'));if(user.role==='admin'&&!db.prepare("SELECT id FROM users WHERE id=? AND role='employee'").get(employeeId))fail(404,'No encontrado.');const readAt=user.role==='admin'?all('staffRead',employeeId)[0]?.date||'':staffReadByAdmin(employeeId);send(res,200,{messages:all('staffMessage',employeeId),readAt});return true;}
  if(p==='/api/staff-chat/messages'&&method==='POST'){if(!['admin','employee'].includes(user.role))fail(404,'No encontrado.');const employeeId=user.role==='employee'?user.id:text(b.employeeId);if(user.role==='admin'&&!db.prepare("SELECT id FROM users WHERE id=? AND role='employee'").get(employeeId))fail(404,'No encontrado.');if(!/^[\w-]{8,100}$/.test(b.idempotencyKey||''))fail(400,'Referencia inválida.');const message=text(b.text,4000),photos=(Array.isArray(b.photos)?b.photos:[]).slice(0,4).map(k=>safeFile(user,k,'image/'));if(!message&&!photos.length)fail(400,'Escribí un mensaje o adjuntá una foto.');const messageId='staff-'+sha(user.id+':'+b.idempotencyKey),old=all('staffMessage',employeeId).find(m=>m.id===messageId);if(old){send(res,200,old);return true;}const result=put('staffMessage',employeeId,{id:messageId,userId:employeeId,employeeId,senderId:user.id,senderName:user.name,senderRole:user.role,text:message,photos,date:now()});if(user.role==='employee')notifyAdmins('Mensaje del equipo',user.name+' escribió a Administración.','/#chat-equipo/'+employeeId,'important');else notify(employeeId,'AMC / Administración','Tenés un mensaje nuevo.','/#chat-equipo','important');send(res,201,result);return true;}
  if(p==='/api/staff-chat/read'&&method==='POST'){if(!['admin','employee'].includes(user.role))fail(404,'No encontrado.');if(user.role==='employee'){put('staffRead',user.id,{id:'staff-read-'+user.id,userId:user.id,date:now()});const noticeIds=markNoticesForRoute(user,'/#chat-equipo');send(res,200,{ok:true,noticeIds});return true;}const employeeId=text(b.employeeId);if(!db.prepare("SELECT id FROM users WHERE id=? AND role='employee' AND active=1").get(employeeId))fail(404,'Empleado no encontrado.');put('staffAdminRead',user.id,{id:'staff-admin-read-'+sha(user.id+':'+employeeId),userId:user.id,employeeId,date:now()});const noticeIds=markNoticesForRoute(user,'/#chat-equipo/'+employeeId);send(res,200,{ok:true,noticeIds});return true;}
  return false;
 };
 return {clientChatIds,chatIds,chatOwn,chatState,chatMedia,chatSummary,clientMessages,staffMessages,staffUnread,staffReadByEmployee,staffReadByAdmin,routeBeforeBody,routeAfterBody};
}
