// Operations share the existing authorization, storage and transaction boundary.
export function featureRoutes({db,all,get,put,transaction,own,chatOwn,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,amount,validDate,now,id,sha}){
 const key=(value,prefix,user)=>{if(!/^[a-zA-Z0-9_-]{8,100}$/.test(value||''))fail(400,'Falta una referencia válida de la operación.');return prefix+sha(user+':'+value);};
 const old=(kind,k)=>{const row=db.prepare('SELECT body FROM docs WHERE kind=? AND id=?').get(kind,k);return row?JSON.parse(row.body):null;};
 const paid=w=>w.payments.reduce((n,p)=>n+p.amount,0);
 return async function route({p,method,b,user,res}){
  let match;
  if(method==='POST'&&p==='/api/admin/requests'){
   requireAdmin(user);const client=db.prepare("SELECT * FROM users WHERE id=? AND role='client'").get(b.userId);if(!client||!text(b.service)||!text(b.description,4000))fail(400,'Elegí un cliente y describí el trabajo.');const requestId=key(b.idempotencyKey,'manual-',user.id),previous=old('request',requestId);if(previous){send(res,200,previous);return true;}const r=put('request',client.id,{id:requestId,userId:client.id,type:'presupuesto',name:client.name,phone:client.phone,town:client.town,service:text(b.service),description:text(b.description,4000),photos:[],status:'En contacto',date:now(),createdBy:user.id});send(res,201,r);return true;
  }
  if(method==='POST'&&(match=p.match(/^\/api\/requests\/([^/]+)\/messages$/))){
   const r=chatOwn(user,get('request',match[1]));const messageId=key(b.idempotencyKey,'msg-',user.id);if(old('message',messageId)){send(res,200,old('message',messageId));return true;}
   const message=text(b.text,4000),files=Array.isArray(b.photos)?b.photos:[];if(files.length>4||(!message&&!files.length))fail(400,'Escribí un mensaje o adjuntá hasta cuatro fotos.');const photos=files.map(k=>safeFile(user,k,'image/'));
   const result=transaction(()=>{const result=put('message',r.userId,{id:messageId,userId:r.userId,requestId:r.id,senderId:user.id,senderName:user.name,senderRole:user.role,text:message,photos,date:now()});if(user.role!=='client')notify(r.userId,'AMC te escribió','Hay un mensaje en tu pedido.','/#mensajes');if(user.role!=='admin')notifyAdmins('Nuevo mensaje',user.name+' escribió sobre '+r.service,'/#mensajes');for(const employeeId of new Set(all('assignment').filter(t=>t.requestId===r.id&&!['Cancelada','Finalizada'].includes(t.status)).map(t=>t.employeeId)))if(employeeId!==user.id)notify(employeeId,'Nuevo mensaje del trabajo',r.service,'/#mensajes');return result;});send(res,201,result);return true;
  }
  if(method==='POST'&&(match=p.match(/^\/api\/quotes\/([^/]+)\/view$/))){const q=own(user,get('quote',match[1]));if(user.role!=='client')fail(403,'Sólo el cliente registra la lectura.');for(const n of all('notice',user.id).filter(n=>!n.read&&n.url?.endsWith('#presupuestos')))put('notice',user.id,{...n,read:true});if(!q.seenAt)transaction(()=>{put('quote',q.userId,{...q,seenAt:now()});notifyAdmins('Presupuesto visto',user.name+' abrió '+q.number);});send(res,200,{ok:true});return true;}
  if(method==='POST'&&(match=p.match(/^\/api\/requests\/([^/]+)\/appointment$/))){
   requireAdmin(user);const r=get('request',match[1]);const duration=Number(b.duration);if(!validDate(b.day)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(b.time||'')||![30,60,90,120,180,240].includes(duration)||!text(b.address,500))fail(400,'Completá fecha, hora, duración y dirección.');
   const start=new Date(b.day+'T'+b.time+':00-03:00').getTime(),end=start+duration*60000;if(start<Date.now())fail(400,'La visita debe programarse para una fecha futura.');const visitId='visit-'+r.id;
   if(all('appointment').some(v=>v.id!==visitId&&['Confirmada','Cambio solicitado'].includes(v.status)&&start<Date.parse(v.endsAt)&&end>Date.parse(v.startsAt)))fail(409,'Ese horario se superpone con otra visita. Elegí otra hora.');
   const previous=old('appointment',visitId);const event={status:'Confirmada',date:now(),day:b.day,time:b.time,duration,address:text(b.address,500)};
   const result=transaction(()=>{const v=put('appointment',r.userId,{id:visitId,userId:r.userId,requestId:r.id,clientName:r.name,service:r.service,...event,startsAt:new Date(start).toISOString(),endsAt:new Date(end).toISOString(),note:text(b.note,2000),history:[...(previous?.history||[]),event]});put('request',r.userId,{...r,status:'Visita confirmada'});notify(r.userId,previous?'Visita reprogramada':'Visita confirmada',b.day+' a las '+b.time+' · '+text(b.address,500),'/#agenda');return v;});send(res,200,result);return true;
  }
  if(method==='POST'&&(match=p.match(/^\/api\/appointments\/([^/]+)\/status$/))){const v=own(user,get('appointment',match[1]));const allowed=user.role==='admin'?['Cancelada','Realizada']:['Cambio solicitado'];if(!allowed.includes(b.status)||!['Confirmada','Cambio solicitado'].includes(v.status))fail(409,'La visita no admite ese cambio.');if(b.status==='Cambio solicitado'&&!text(b.reason))fail(400,'Contanos qué horario necesitás.');transaction(()=>{put('appointment',v.userId,{...v,status:b.status,reason:text(b.reason,2000),history:[...v.history,{status:b.status,reason:text(b.reason,2000),date:now()}]});if(user.role==='admin')notify(v.userId,'Novedades de tu visita',b.status,'/#agenda');else notifyAdmins('Cambio de visita solicitado',user.name+' pidió otro horario.');});send(res,200,{ok:true});return true;}
  if(method==='POST'&&(match=p.match(/^\/api\/works\/([^/]+)\/extras$/))){requireAdmin(user);const w=get('work',match[1]),extraId=key(b.idempotencyKey,'extra-',user.id);const previous=old('extra',extraId);if(previous){send(res,200,previous);return true;}if(!text(b.title)||!text(b.description,4000))fail(400,'Describí el trabajo adicional y su alcance.');const total=amount(b.amount);const result=transaction(()=>{const x=put('extra',w.userId,{id:extraId,workId:w.id,userId:w.userId,title:text(b.title),description:text(b.description,4000),amount:total,status:'Pendiente de aprobación',date:now()});notify(w.userId,'Un adicional necesita tu aprobación','Revisá el trabajo y su importe antes de aceptar.','/#adicionales');return x;});send(res,201,result);return true;}
  if(method==='POST'&&(match=p.match(/^\/api\/extras\/([^/]+)\/reply$/))){const x=own(user,get('extra',match[1]));if(user.role!=='client')fail(403,'La respuesta corresponde al cliente.');if(!['Aceptado','Rechazado'].includes(b.status))fail(400,'Respuesta inválida.');if(x.status===b.status){send(res,200,{ok:true});return true;}if(x.status!=='Pendiente de aprobación')fail(409,'Este adicional ya fue respondido.');transaction(()=>{put('extra',x.userId,{...x,status:b.status,reply:text(b.message,2000),repliedAt:now()});if(b.status==='Aceptado'){const w=get('work',x.workId);put('work',w.userId,{...w,baseBudget:w.baseBudget??w.budget,budget:Math.round((w.budget+x.amount)*100)/100});}notifyAdmins('Respuesta a trabajo adicional',user.name+' · '+b.status);});send(res,200,{ok:true});return true;}
  if(method==='POST'&&(match=p.match(/^\/api\/works\/([^/]+)\/receipts$/))){
   const w=own(user,get('work',match[1]));if(user.role!=='client')fail(403,'El comprobante se carga desde la cuenta del cliente.');const receiptId=key(b.idempotencyKey,'receipt-',user.id),previous=old('receipt',receiptId);if(previous){send(res,200,previous);return true;}const total=amount(b.amount);if(total>w.budget-paid(w)+.001||!validDate(b.day)||b.day>now().slice(0,10)||!text(b.reference))fail(400,'Revisá importe, fecha y referencia. El importe no puede superar el saldo.');const file=safeFile(user,b.fileId);const result=transaction(()=>{const r=put('receipt',w.userId,{id:receiptId,workId:w.id,userId:w.userId,amount:total,day:b.day,reference:text(b.reference,500),file,status:'Pendiente',date:now()});notifyAdmins('Comprobante recibido',user.name+' cargó un comprobante para revisar.');return r;});send(res,201,result);return true;
  }
  if(method==='POST'&&(match=p.match(/^\/api\/receipts\/([^/]+)\/review$/))){requireAdmin(user);const r=get('receipt',match[1]);if(!['Confirmado','Rechazado'].includes(b.status))fail(400,'Estado inválido.');if(r.status===b.status){send(res,200,{ok:true});return true;}if(r.status!=='Pendiente')fail(409,'El comprobante ya fue revisado.');if(b.status==='Rechazado'&&!text(b.reason))fail(400,'Indicá el motivo del rechazo.');transaction(()=>{const w=get('work',r.workId);if(b.status==='Confirmado'){if(r.amount>w.budget-paid(w)+.001)fail(409,'El saldo cambió. Verificá que no hayas registrado este pago previamente.');put('work',w.userId,{...w,payments:[...w.payments,{id:id(),key:r.id,receiptId:r.id,amount:r.amount,date:r.day,description:'Comprobante confirmado · '+r.reference}]});}put('receipt',r.userId,{...r,status:b.status,reason:text(b.reason,2000),reviewedAt:now(),reviewedBy:user.id});notify(r.userId,b.status==='Confirmado'?'Pago confirmado':'Comprobante observado',b.status==='Confirmado'?'El pago ya está descontado de tu saldo.':text(b.reason,2000),'/#comprobantes');});send(res,200,{ok:true});return true;}
  return false;
 };
}
