export function fieldworkFeatures({all,get,put,transaction,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,validDate,now,id,sha}){
 const scoped=(kind,u)=>u.role==='admin'?all(kind):u.role==='employee'?all(kind).filter(x=>x.employeeId===u.id&&all('assignment',u.id).some(t=>t.id===x.assignmentId)):[];
 const employeeTask=(u,k)=>{const t=get('assignment',k);if(u.role!=='employee'||t.employeeId!==u.id)fail(404,'Asignación no encontrada.');if(t.status==='Cancelada')fail(409,'La asignación fue cancelada.');return t;};
 const key=(u,k,kind)=>{if(!/^[\w-]{8,100}$/.test(k||''))fail(400,'Referencia inválida.');return kind+'-'+sha(u.id+':'+k);};
 async function route({p,method,b,user,res}){let m;
  if(method==='POST'&&(m=p.match(/^\/api\/assignments\/([^/]+)\/(visit-sheet|materials)$/))){const t=employeeTask(user,m[1]),kind=m[2]==='visit-sheet'?'visitSheet':'materialRequest',k=key(user,b.idempotencyKey,kind),old=all(kind).find(x=>x.id===k);if(old){send(res,200,old);return true;}
   let fields;if(kind==='visitSheet'){if(!validDate(b.day)||b.day>now().slice(0,10)||!text(b.scope,4000)||!text(b.measurements,4000)||!text(b.materials,4000)||!text(b.access,2000))fail(400,'Completá fecha, trabajo, medidas, materiales y acceso al domicilio.');const files=Array.isArray(b.photos)?b.photos:[];if(files.length>4)fail(400,'Adjuntá hasta cuatro fotos.');fields={day:b.day,scope:text(b.scope,4000),measurements:text(b.measurements,4000),materials:text(b.materials,4000),access:text(b.access,2000),observations:text(b.observations,4000),photos:files.map(k=>safeFile(user,k,'image/'))};}
   else{if(!validDate(b.neededBy)||!text(b.items,4000)||!text(b.reason,2000))fail(400,'Indicá materiales, cantidades, fecha necesaria y motivo.');fields={neededBy:b.neededBy,items:text(b.items,4000),reason:text(b.reason,2000),urgent:b.urgent===true};}
   const result=transaction(()=>{const record=put(kind,user.id,{id:k,employeeId:user.id,employeeName:user.name,assignmentId:t.id,requestId:t.requestId,clientName:t.clientName,service:t.service,...fields,status:'Pendiente',date:now()});notifyAdmins(kind==='visitSheet'?'Ficha de visita recibida':'Pedido de materiales',user.name+' · '+t.clientName);return record;});send(res,201,result);return true;
  }
  if(method==='POST'&&(m=p.match(/^\/api\/visit-sheets\/([^/]+)\/review$/))){requireAdmin(user);const x=get('visitSheet',m[1]);if(x.status!=='Revisada')transaction(()=>{put('visitSheet',x.employeeId,{...x,status:'Revisada',reviewedAt:now(),reviewedBy:user.id});notify(x.employeeId,'Ficha revisada por AMC',x.clientName,'/#fichas');});send(res,200,{ok:true});return true;}
  if(method==='POST'&&(m=p.match(/^\/api\/material-requests\/([^/]+)\/review$/))){requireAdmin(user);const x=get('materialRequest',m[1]);if(x.status===b.status){send(res,200,{ok:true});return true;}const allowed={Pendiente:['Aprobado','Rechazado'],Aprobado:['Comprado'],Comprado:['Entregado']};if(!allowed[x.status]?.includes(b.status))fail(409,'Ese cambio no corresponde al estado actual.');if(b.status==='Rechazado'&&!text(b.reason))fail(400,'Indicá por qué se rechaza el pedido.');let purchaseId=x.purchaseId||null;if(b.status==='Comprado'){const purchase=get('purchase',b.purchaseId);if(purchase.requestId!==x.requestId)fail(400,'La compra debe pertenecer al mismo pedido del cliente.');purchaseId=purchase.id;}
   transaction(()=>{put('materialRequest',x.employeeId,{...x,status:b.status,purchaseId,reviewReason:text(b.reason,2000),history:[...(x.history||[]),{status:b.status,date:now(),actor:user.id}],updatedAt:now()});notify(x.employeeId,'Materiales · '+b.status,x.clientName,'/#materiales');});send(res,200,{ok:true});return true;
  }return false;
 }
 return {route,media:(u,p)=>scoped('visitSheet',u).some(x=>x.photos.includes(p)),state:u=>({visitSheets:scoped('visitSheet',u).map(x=>u.role==='admin'?x:(({requestId,reviewedBy,...safe})=>safe)(x)),materialRequests:scoped('materialRequest',u).map(x=>u.role==='admin'?x:(({requestId,purchaseId,history,...safe})=>safe)(x))})};
}
