import {rangeSlots,businessTime,sameTeam} from './public/calendar-rules.js';
export function planningFeatures({db,all,get,put,transaction,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,validDate,now,id,sha}){
 const appearance=()=>all('appearance')[0]||{id:'public-appearance',title:'Tu casa.\nTu proyecto.\nTodo en AMC.',subtitle:'Desde la primera idea hasta el último detalle, un lugar para conversar, presupuestar y seguir tu obra.',photos:[]};
 const publicMedia=p=>appearance().photos.some(x=>x.url===p);
 const sourceEvents=()=>{const bookings=all('calendarBooking').filter(x=>['Tentativa','Propuesta','Confirmada'].includes(x.status)).map(x=>({...x,source:'calendar'})),linked=new Set(bookings.filter(x=>x.workId).map(x=>x.workId)),events=[...bookings];
  for(const w of all('work'))if(w.start&&w.end&&!linked.has(w.id)){try{events.push({id:'work-'+w.id,source:'work',workId:w.id,requestId:all('quote').find(q=>q.id===w.quoteId)?.requestId,title:w.title,clientName:db.prepare('SELECT name FROM users WHERE id=?').get(w.userId)?.name||'',teamIds:[],start:w.start,end:w.end,slot:'Día completo',kind:'Obra',status:'Confirmada',occurrences:rangeSlots(w.start,w.end)});}catch{}}
  for(const t of all('assignment'))if(t.status!=='Cancelada')events.push({id:'assignment-'+t.id,source:'assignment',requestId:t.requestId,title:t.type+' · '+t.service,clientName:t.clientName,teamIds:[t.employeeId],start:t.day,end:t.day,slot:Number(t.time.slice(0,2))<13?'Mañana':'Tarde',kind:'Asignación',status:'Confirmada',occurrences:[{day:t.day,part:Number(t.time.slice(0,2))<13?'Mañana':'Tarde'}],outsideHours:!businessTime(t.day,t.time)});
  for(const v of all('appointment'))if(['Confirmada','Cambio solicitado'].includes(v.status)){const minutes=Number(v.time.slice(0,2))*60+Number(v.time.slice(3)),parts=[];if(minutes<780)parts.push({day:v.day,part:'Mañana'});if(minutes+v.duration>780)parts.push({day:v.day,part:'Tarde'});events.push({id:'visit-'+v.id,source:'appointment',requestId:v.requestId,title:'Visita · '+v.service,clientName:v.clientName,teamIds:[],start:v.day,end:v.day,slot:'Visita',kind:'Visita',status:'Confirmada',occurrences:parts,outsideHours:!businessTime(v.day,v.time,v.duration)});}
  return events;
 };
 function validateTime(day,time,duration=1){if(!validDate(day)||!businessTime(day,time,duration))fail(400,'Horario laboral: lunes a viernes de 9 a 18; sábados de 9 a 13. Los domingos no se trabaja.');}
 function conflict(booking,excludeId){const occupied=new Set(booking.occurrences.map(x=>x.day+':'+x.part));return sourceEvents().find(x=>x.id!==excludeId&&!(booking.workId&&x.workId===booking.workId)&&!(booking.requestId&&x.requestId===booking.requestId&&x.kind!=='Bloqueo')&&sameTeam(x.teamIds,booking.teamIds)&&x.occurrences.some(v=>occupied.has(v.day+':'+v.part)));}
 function clearDate(b){if(b.workId){const w=get('work',b.workId);if(w.calendarBookingId===b.id)put('work',w.userId,{...w,start:'',end:'',calendarBookingId:null});}if(b.requestId){const r=get('request',b.requestId);if(r.calendarBookingId===b.id)put('request',r.userId,{...r,scheduledStart:'',scheduledEnd:'',calendarBookingId:null});}}
 async function route({p,method,b,user,res}){let m;
  if(method==='POST'&&(m=p.match(/^\/api\/date-proposals\/([^/]+)\/reply$/))){
   const booking=get('calendarBooking',m[1]);const r=booking.requestId?get('request',booking.requestId):null;
   if(user.role!=='client'||!r||r.userId!==user.id)fail(404,'Propuesta no disponible.');
   if(booking.status!=='Propuesta'||b.revision!==booking.updatedAt)fail(409,'La propuesta cambió. Volvé a abrir la ficha.');
   if(!['Confirmada','Cambio solicitado'].includes(b.status))fail(400,'Respuesta inválida.');
   if(b.status==='Cambio solicitado'&&!text(b.message,2000))fail(400,'Indicá qué fecha te serviría.');
   if(b.status==='Confirmada'&&conflict(booking,booking.id))fail(409,'Esa fecha ya no está disponible. Pedile otra a AMC.');
   transaction(()=>{put('calendarBooking','',{...booking,status:b.status,reply:text(b.message,2000),repliedAt:now()});
    if(b.status==='Confirmada'){put('request',r.userId,{...r,scheduledStart:booking.start,scheduledEnd:booking.end,calendarBookingId:booking.id});if(booking.workId){const w=get('work',booking.workId);put('work',w.userId,{...w,start:booking.start,end:booking.end,calendarBookingId:booking.id});}}
    notifyAdmins('Respuesta a fecha de comienzo',r.name+' · '+b.status,'/#solicitud/'+r.id);notify(r.userId,b.status==='Confirmada'?'Comienzo confirmado':'Pedido de cambio enviado',booking.start+' al '+booking.end,'/#solicitud/'+r.id);
   });send(res,200,{ok:true});return true;
  }
  if(p==='/api/appearance'&&method==='POST'){requireAdmin(user);if(!text(b.title,160)||!text(b.subtitle,600)||!Array.isArray(b.photos)||b.photos.length>5)fail(400,'Completá el título, presentación y hasta cinco fotos.');const current=appearance();const photos=b.photos.map(x=>({url:current.photos.some(p=>p.url==='/media/'+x.id)?'/media/'+x.id:safeFile(user,x.id,'image/'),caption:text(x.caption,200)}));const result=put('appearance','',{id:'public-appearance',title:text(b.title,160),subtitle:text(b.subtitle,600),photos,updatedAt:now()});send(res,200,result);return true;}
  if(method==='POST'&&(p==='/api/calendar-bookings'||(m=p.match(/^\/api\/calendar-bookings\/([^/]+)\/edit$/)))){requireAdmin(user);let old=m?get('calendarBooking',m[1]):null;if(old?.status==='Cancelada')fail(409,'La reserva fue cancelada. Creá otra.');if(!old&&!/^[\w-]{8,100}$/.test(b.idempotencyKey||''))fail(400,'Referencia inválida.');const key=old?.id||'booking-'+sha(user.id+':'+b.idempotencyKey);if(!old){const existing=all('calendarBooking').find(x=>x.id===key);if(existing){send(res,200,existing);return true;}}
   if(!['Obra','Reserva','Bloqueo'].includes(b.kind)||!['Tentativa','Propuesta','Confirmada'].includes(b.status)||!['Mañana','Tarde','Día completo'].includes(b.slot)||!validDate(b.start)||!validDate(b.end)||!text(b.title))fail(400,'Completá tipo, estado, título, fechas y franja.');const teamIds=[...new Set(Array.isArray(b.teamIds)?b.teamIds:[])];if(teamIds.length>50||teamIds.some(k=>!db.prepare("SELECT id FROM users WHERE id=? AND role IN ('employee','admin') AND active=1").get(k)))fail(400,'Elegí empleados activos.');let workId=null,requestId=null,clientName='';if(b.kind==='Obra'){const w=get('work',b.workId);workId=w.id;requestId=get('quote',w.quoteId).requestId;}else if(b.kind==='Reserva'&&b.requestId)requestId=get('request',b.requestId).id;if(b.status==='Propuesta'&&!requestId)fail(400,'Elegí una obra o un cliente para enviar la propuesta.');if(requestId)clientName=get('request',requestId).name;
   let occurrences;try{occurrences=rangeSlots(b.start,b.end,b.slot);}catch(e){fail(400,e.message);}if(!occurrences.length)fail(400,'Ese período no tiene horas laborales. Domingo cerrado; sábado sólo mañana.');const booking={id:key,kind:b.kind,status:b.status,title:text(b.title),notes:text(b.notes,2000),teamIds,workId,requestId,clientName,start:occurrences[0].day,end:occurrences.at(-1).day,slot:b.slot,occurrences,date:old?.date||now(),updatedAt:now()};const clash=conflict(booking,old?.id);if(clash)fail(409,'Se superpone con '+clash.title+' ('+clash.clientName+'). Cambiá el equipo, la franja o las fechas.');
   const result=transaction(()=>{if(old)clearDate(old);put('calendarBooking','',booking);if(booking.status==='Propuesta'){const r=get('request',requestId);notify(r.userId,'Propuesta de comienzo',booking.start+' al '+booking.end+'. Confirmá o pedí otra fecha.','/#solicitud/'+requestId);}if(booking.status==='Confirmada'&&requestId){const r=get('request',requestId);put('request',r.userId,{...r,scheduledStart:booking.start,scheduledEnd:booking.end,calendarBookingId:key});if(workId){const w=get('work',workId);put('work',w.userId,{...w,start:booking.start,end:booking.end,calendarBookingId:key});}notify(r.userId,'Fecha de trabajo confirmada',booking.start+' al '+booking.end+' · '+booking.slot+'. Domingos no laborales; sábados sólo mañana.','/#perfil');}return booking;});send(res,old?200:201,result);return true;
  }
  if(method==='POST'&&(m=p.match(/^\/api\/calendar-bookings\/([^/]+)\/cancel$/))){requireAdmin(user);const booking=get('calendarBooking',m[1]);if(booking.status!=='Cancelada')transaction(()=>{clearDate(booking);put('calendarBooking','',{...booking,status:'Cancelada',updatedAt:now()});if(booking.requestId&&booking.status==='Confirmada'){const r=get('request',booking.requestId);notify(r.userId,'Fecha de trabajo por reprogramar','AMC reprogramará la fecha previamente acordada.','/#perfil');}});send(res,200,{ok:true});return true;}
  return false;
 }
 return {route,appearance,publicMedia,validateTime,state:u=>({...(u.role==='admin'?{calendarEvents:sourceEvents(),calendarBookings:all('calendarBooking')}:{}),dateProposals:all('calendarBooking').filter(b=>b.requestId&&(u.role==='admin'||(u.role==='client'&&get('request',b.requestId).userId===u.id))).map(b=>({id:b.id,requestId:b.requestId,start:b.start,end:b.end,slot:b.slot,status:b.status,reply:b.reply||'',revision:b.updatedAt}))}),validateWork:(w,start,end)=>{if(w.calendarBookingId&&(start!==w.start||end!==w.end))fail(400,'Modificá las fechas de esta obra desde el calendario.');}};
}
