import {createECDH,generateKeyPairSync,createPrivateKey,sign,randomBytes,createHmac,createCipheriv} from 'node:crypto';
import {readFileSync} from 'node:fs';
const enc=v=>Buffer.from(v).toString('base64url'),hmac=(key,data)=>createHmac('sha256',key).update(data).digest();
const expand=(key,info,length)=>hmac(key,Buffer.concat([info,Buffer.from([1])])).subarray(0,length);
export function pushKeys(db){const row=db.prepare("SELECT value FROM config WHERE key='vapid'").get();if(row)return JSON.parse(row.value);const {privateKey,publicKey}=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),jwk=publicKey.export({format:'jwk'});const keys={privateKey:privateKey.export({type:'pkcs8',format:'pem'}).toString(),publicKey:Buffer.concat([Buffer.from([4]),Buffer.from(jwk.x,'base64url'),Buffer.from(jwk.y,'base64url')]).toString('base64url')};db.prepare("INSERT INTO config VALUES('vapid',?)").run(JSON.stringify(keys));return keys;}
export function validSubscription(kind,s){if(!s||typeof s!=='object')return false;if(kind==='android')return typeof s.token==='string'&&s.token.length>=20&&s.token.length<4096&&/^[A-Za-z0-9:_-]+$/.test(s.token);try{const u=new URL(s.endpoint),allowed=['fcm.googleapis.com','updates.push.services.mozilla.com','web.push.apple.com'];const hostOk=allowed.includes(u.hostname)||u.hostname.endsWith('.notify.windows.com');return u.protocol==='https:'&&!u.port&&!u.username&&!u.password&&hostOk&&s.endpoint.length<4096&&Buffer.from(s.keys.p256dh,'base64url').length===65&&Buffer.from(s.keys.auth,'base64url').length===16;}catch{return false;}}
export function encryptWebPush(subscription,payload){const ua=Buffer.from(subscription.keys.p256dh,'base64url'),auth=Buffer.from(subscription.keys.auth,'base64url'),ecdh=createECDH('prime256v1');ecdh.generateKeys();const server=ecdh.getPublicKey(),shared=ecdh.computeSecret(ua),prkKey=hmac(auth,shared),ikm=expand(prkKey,Buffer.concat([Buffer.from('WebPush: info\0'),ua,server]),32),salt=randomBytes(16),prk=hmac(salt,ikm),cek=expand(prk,Buffer.from('Content-Encoding: aes128gcm\0'),16),nonce=expand(prk,Buffer.from('Content-Encoding: nonce\0'),12),cipher=createCipheriv('aes-128-gcm',cek,nonce),plaintext=Buffer.from(JSON.stringify(payload));if(plaintext.length>3000)throw Error('Aviso demasiado largo.');const encrypted=Buffer.concat([cipher.update(Buffer.concat([plaintext,Buffer.from([2])])),cipher.final(),cipher.getAuthTag()]);const rs=Buffer.alloc(4);rs.writeUInt32BE(4096);return Buffer.concat([salt,rs,Buffer.from([server.length]),server,encrypted]);}
function vapid(endpoint,keys){const token=enc(JSON.stringify({typ:'JWT',alg:'ES256'}))+'.'+enc(JSON.stringify({aud:new URL(endpoint).origin,exp:Math.floor(Date.now()/1000)+3600,sub:process.env.AMC_PUSH_CONTACT||process.env.AMC_ORIGIN||'https://localhost'}));return token+'.'+sign('sha256',Buffer.from(token),{key:createPrivateKey(keys.privateKey),dsaEncoding:'ieee-p1363'}).toString('base64url');}
let accessToken=null;
async function fcmToken(account){if(accessToken&&accessToken.expires>Date.now()+60000)return accessToken.token;const seconds=Math.floor(Date.now()/1000),unsigned=enc(JSON.stringify({alg:'RS256',typ:'JWT'}))+'.'+enc(JSON.stringify({iss:account.client_email,scope:'https://www.googleapis.com/auth/firebase.messaging',aud:'https://oauth2.googleapis.com/token',iat:seconds,exp:seconds+3600}));const assertion=unsigned+'.'+sign('RSA-SHA256',Buffer.from(unsigned),account.private_key).toString('base64url');const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('No se pudo autorizar Firebase.');const data=await response.json();accessToken={token:data.access_token,expires:Date.now()+Number(data.expires_in)*1000};return accessToken.token;}
export async function deliver(kind,subscription,payload,keys,sound=true){if(!validSubscription(kind,subscription))throw Object.assign(Error('Dispositivo inválido.'),{gone:true});let response;if(kind==='web'){response=await fetch(subscription.endpoint,{method:'POST',redirect:'error',headers:{Authorization:`vapid t=${vapid(subscription.endpoint,keys)}, k=${keys.publicKey}`,TTL:'86400',Urgency:'high','Content-Encoding':'aes128gcm','Content-Type':'application/octet-stream'},body:encryptWebPush(subscription,{...payload,silent:!sound}),signal:AbortSignal.timeout(15000)});}else{if(!process.env.AMC_FIREBASE_CREDENTIALS)throw Error('Falta configurar Firebase para Android.');const account=JSON.parse(readFileSync(process.env.AMC_FIREBASE_CREDENTIALS,'utf8'));if(!/^[a-z0-9-]+$/.test(account.project_id))throw Error('Proyecto Firebase inválido.');const token=await fcmToken(account);response=await fetch(`https://fcm.googleapis.com/v1/projects/${account.project_id}/messages:send`,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({message:{token:subscription.token,data:{id:payload.id,url:payload.url,sound:String(sound),priority:payload.priority||'normal'},notification:{title:payload.title,body:payload.body},android:{priority:'HIGH',notification:{channel_id:sound?(payload.priority==='urgent'?'amc_urgent':'amc_updates'):'amc_silent',default_sound:sound,default_vibrate_timings:sound,tag:payload.id}}}}),signal:AbortSignal.timeout(15000)});}if(!response.ok)throw Object.assign(Error('El proveedor rechazó el aviso ('+response.status+').'),{gone:response.status===404||response.status===410});}
