import {randomBytes} from 'node:crypto';
export async function sendRecoveryMail(email,url){if(!process.env.AMC_RESEND_API_KEY||!process.env.AMC_MAIL_FROM)throw Error('Correo sin configurar');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+process.env.AMC_RESEND_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.AMC_MAIL_FROM,to:[email],subject:'Recuperar tu acceso a AMC',text:'Solicitaste cambiar tu contraseña de AMC. Este enlace vence en 15 minutos y se usa una sola vez:\n\n'+url+'\n\nSi no lo solicitaste, ignorá este mensaje.'}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('No se pudo entregar el correo');}
export function recoveryFeatures({db,all,put,transaction,requireAdmin,verifyAdmin,notifyAdmins,send,fail,text,sha,passwordHash,origin,clock=Date.now,sendRecovery=sendRecoveryMail}){
 db.exec('CREATE TABLE IF NOT EXISTS password_resets(token TEXT PRIMARY KEY,userId TEXT NOT NULL,expires INTEGER NOT NULL,fingerprint TEXT NOT NULL)');
 const generic={ok:true,message:'Si la cuenta está activa, se gestionará la recuperación. Revisá tu correo o contactá a AMC.'};
 function issue(u){const token=randomBytes(32).toString('hex');db.prepare('DELETE FROM password_resets WHERE userId=? OR expires<=?').run(u.id,clock());db.prepare('INSERT INTO password_resets VALUES(?,?,?,?)').run(sha(token),u.id,clock()+900000,sha(u.password));return origin+'/#restablecer?token='+token;}
 async function route({p,method,b,user,res}){
  if(p==='/api/forgot-password'&&method==='POST'){const u=db.prepare('SELECT * FROM users WHERE email=? AND active=1').get(text(b.email).toLowerCase());if(u){const k='recovery-'+u.id,prior=all('recoveryRequest').find(x=>x.id===k);if(!prior||clock()-Date.parse(prior.date)>=900000||prior.status==='Resuelta'){const record={id:k,userId:u.id,email:u.email,name:u.name,date:new Date(clock()).toISOString(),status:'Pendiente'};put('recoveryRequest','',record);notifyAdmins('Recuperación de acceso solicitada',u.name+' necesita recuperar su cuenta.');if(sendRecovery!==sendRecoveryMail||process.env.AMC_RESEND_API_KEY&&process.env.AMC_MAIL_FROM){const link=issue(u);Promise.resolve().then(()=>sendRecovery(u.email,link)).then(()=>{const current=all('recoveryRequest').find(x=>x.id===k);if(current?.date===record.date&&current.status==='Pendiente')put('recoveryRequest','',{...record,status:'Correo enviado'});}).catch(()=>{const current=all('recoveryRequest').find(x=>x.id===k);if(current?.date===record.date&&current.status==='Pendiente')put('recoveryRequest','',{...record,status:'Requiere asistencia de AMC'});});}}}send(res,200,generic);return true;}
  if(p==='/api/reset-password'&&method==='POST'){if(typeof b.password!=='string'||b.password.length<8||b.password.length>200)fail(400,'Usá una contraseña de 8 a 200 caracteres.');const record=db.prepare('SELECT * FROM password_resets WHERE token=? AND expires>?').get(sha(text(b.token,200)),clock()),u=record?db.prepare('SELECT * FROM users WHERE id=? AND active=1').get(record.userId):null;if(!u||record.fingerprint!==sha(u.password))fail(400,'El enlace venció, ya se usó o no es válido. Solicitá uno nuevo.');transaction(()=>{db.prepare('UPDATE users SET password=? WHERE id=?').run(passwordHash(b.password),u.id);db.prepare('DELETE FROM password_resets WHERE userId=?').run(u.id);db.prepare('DELETE FROM sessions WHERE userId=?').run(u.id);db.prepare('DELETE FROM delivery WHERE deviceId IN (SELECT id FROM devices WHERE userId=?)').run(u.id);db.prepare('DELETE FROM devices WHERE userId=?').run(u.id);const prior=all('recoveryRequest').find(x=>x.userId===u.id);if(prior)put('recoveryRequest','',{...prior,status:'Resuelta'});});send(res,200,{ok:true});return true;}
  if(p==='/api/recovery-link'&&method==='POST'){verifyAdmin(user,b.adminPassword);const u=db.prepare('SELECT * FROM users WHERE id=? AND active=1').get(b.userId);if(!u)fail(404,'Cuenta no disponible.');const url=issue(u);send(res,200,{url,expiresInMinutes:15});return true;}return false;
 }
 return {route,state:u=>({recoveryRequests:u.role==='admin'?all('recoveryRequest'):[]})};
}
