import {randomBytes,randomInt} from 'node:crypto';
export async function sendRecoveryMail(email,{code}){if(!process.env.AMC_RESEND_API_KEY||!process.env.AMC_MAIL_FROM)throw Error('Correo sin configurar');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+process.env.AMC_RESEND_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.AMC_MAIL_FROM,to:[email],subject:'Código para recuperar tu acceso a AMC',text:'Tu código de recuperación de AMC es: '+code+'\n\nVence en 10 minutos y se usa una sola vez. Si no lo solicitaste, ignorá este mensaje.'}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('No se pudo entregar el correo');}
export function recoveryFeatures({db,all,put,transaction,requireAdmin,verifyAdmin,notifyAdmins,send,fail,text,sha,passwordHash,origin,clock=Date.now,sendRecovery=sendRecoveryMail}){
 db.exec('CREATE TABLE IF NOT EXISTS password_resets(token TEXT PRIMARY KEY,userId TEXT NOT NULL,expires INTEGER NOT NULL,fingerprint TEXT NOT NULL)');
 db.exec('CREATE TABLE IF NOT EXISTS recovery_codes(challenge TEXT PRIMARY KEY,userId TEXT NOT NULL,codeHash TEXT NOT NULL,expires INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,fingerprint TEXT NOT NULL)');
 const generic='Si la cuenta está activa, vas a recibir un código por correo. Vence en 10 minutos.';
 function issueLink(u){const token=randomBytes(32).toString('hex');db.prepare('DELETE FROM password_resets WHERE userId=? OR expires<=?').run(u.id,clock());db.prepare('INSERT INTO password_resets VALUES(?,?,?,?)').run(sha(token),u.id,clock()+900000,sha(u.password));return origin+'/#restablecer?token='+token;}
 function issueCode(u){const challenge=randomBytes(32).toString('hex'),code=String(randomInt(0,1000000)).padStart(6,'0');db.prepare('DELETE FROM recovery_codes WHERE userId=? OR expires<=?').run(u.id,clock());db.prepare('INSERT INTO recovery_codes(challenge,userId,codeHash,expires,attempts,fingerprint) VALUES(?,?,?,?,?,?)').run(sha(challenge),u.id,sha(challenge+':'+code),clock()+600000,0,sha(u.password));return {challenge,code};}
 function finish(u){db.prepare('DELETE FROM password_resets WHERE userId=?').run(u.id);db.prepare('DELETE FROM recovery_codes WHERE userId=?').run(u.id);db.prepare('DELETE FROM sessions WHERE userId=?').run(u.id);db.prepare('DELETE FROM delivery WHERE deviceId IN (SELECT id FROM devices WHERE userId=?)').run(u.id);db.prepare('DELETE FROM devices WHERE userId=?').run(u.id);const prior=all('recoveryRequest').find(x=>x.userId===u.id);if(prior)put('recoveryRequest','',{...prior,status:'Resuelta'});}
 async function route({p,method,b,user,res}){
  if(p==='/api/forgot-password'&&method==='POST'){const unknownChallenge=randomBytes(32).toString('hex'),u=db.prepare('SELECT * FROM users WHERE email=? AND active=1').get(text(b.email).toLowerCase());if(u){const k='recovery-'+u.id,record={id:k,userId:u.id,email:u.email,name:u.name,date:new Date(clock()).toISOString(),status:'Pendiente'},issued=issueCode(u);put('recoveryRequest','',record);notifyAdmins('Recuperación de acceso solicitada',u.name+' necesita recuperar su cuenta.');Promise.resolve().then(()=>sendRecovery(u.email,{code:issued.code})).then(()=>{const current=all('recoveryRequest').find(x=>x.id===k);if(current?.date===record.date&&current.status==='Pendiente')put('recoveryRequest','',{...record,status:'Código enviado'});}).catch(()=>{const current=all('recoveryRequest').find(x=>x.id===k);if(current?.date===record.date&&current.status==='Pendiente')put('recoveryRequest','',{...record,status:'Requiere asistencia de AMC'});});return send(res,200,{ok:true,message:generic,challenge:issued.challenge});}send(res,200,{ok:true,message:generic,challenge:unknownChallenge});return true;}
  if(p==='/api/reset-password'&&method==='POST'){if(typeof b.password!=='string'||b.password.length<8||b.password.length>200)fail(400,'Usá una contraseña de 8 a 200 caracteres.');let record,u;if(b.challenge||b.code){const challenge=text(b.challenge,200),code=text(b.code,6);record=db.prepare('SELECT * FROM recovery_codes WHERE challenge=? AND expires>?').get(sha(challenge),clock());if(record){if(record.attempts>=5)fail(400,'El código quedó bloqueado. Solicitá uno nuevo.');if(!/^\d{6}$/.test(code)||record.codeHash!==sha(challenge+':'+code)){db.prepare('UPDATE recovery_codes SET attempts=attempts+1 WHERE challenge=?').run(sha(challenge));fail(400,'El código no es válido. Revisalo o solicitá uno nuevo.');}u=db.prepare('SELECT * FROM users WHERE id=? AND active=1').get(record.userId);}}else{record=db.prepare('SELECT * FROM password_resets WHERE token=? AND expires>?').get(sha(text(b.token,200)),clock());u=record?db.prepare('SELECT * FROM users WHERE id=? AND active=1').get(record.userId):null;}if(!u||record.fingerprint!==sha(u.password))fail(400,'El código venció, ya se usó o no es válido. Solicitá uno nuevo.');transaction(()=>{db.prepare('UPDATE users SET password=? WHERE id=?').run(passwordHash(b.password),u.id);finish(u);});send(res,200,{ok:true});return true;}
  if(p==='/api/recovery-link'&&method==='POST'){verifyAdmin(user,b.adminPassword);const u=db.prepare('SELECT * FROM users WHERE id=? AND active=1').get(b.userId);if(!u)fail(404,'Cuenta no disponible.');const url=issueLink(u);send(res,200,{url,expiresInMinutes:15});return true;}return false;
 }
 return {route,state:u=>({recoveryRequests:u.role==='admin'?all('recoveryRequest'):[]})};
}
