import {staticResponse} from './static-response.mjs';
import {PostgresDatabase} from './postgres-db.mjs';
import {planningFeatures} from './planning.mjs';
import {recoveryFeatures} from './recovery.mjs';
import {closureFeatures} from './closure.mjs';
import {fieldworkFeatures} from './fieldwork.mjs';
import {quoteLifecycle} from './quote-lifecycle.mjs';
import http from 'node:http';
import {teamFeatures} from './team.mjs';
import {featureRoutes} from './features.mjs';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID,randomBytes,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {readFileSync,mkdirSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {pushKeys,deliver,validSubscription} from './push.mjs';
const ROOT=path.dirname(fileURLToPath(import.meta.url));
export const services=['Albañilería','Revoques','Cerámicos y porcelanato','Pintura','Plomería','Electricidad','Reparaciones'];
const now=()=>new Date().toISOString(),id=()=>randomUUID(),sha=v=>createHash('sha256').update(v).digest('hex');
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const text=(v,max=200)=>typeof v==='string'?v.trim().slice(0,max):'';
const amount=v=>{if(!Number.isFinite(Number(v))||Number(v)<=0||Number(v)>1e10)fail(400,'Importe inválido.');return Math.round(Number(v)*100)/100;};
const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(v||'')&&!isNaN(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
export function createApp({dbPath=path.join(ROOT,'data/amc.sqlite'),demo=false,origin='http://localhost:4180',clock=Date.now,sendRecovery}={}){
 if(dbPath!==':memory:')mkdirSync(path.dirname(dbPath),{recursive:true});
 const testUrl=process.env.NODE_ENV==='test'?process.env.AMC_TEST_DATABASE_URL:null;const remoteUrl=testUrl||process.env.AMC_DATABASE_URL;const db=remoteUrl?new PostgresDatabase(remoteUrl,{schema:testUrl?'amc_test_'+(dbPath===':memory:'?id().replaceAll('-',''):sha(dbPath).slice(0,24)):'amc_data',test:!!testUrl,caFile:process.env.AMC_DATABASE_CA_FILE}):new DatabaseSync(dbPath);db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
 CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT,phone TEXT,town TEXT,role TEXT NOT NULL,password TEXT NOT NULL,sound INTEGER DEFAULT 1);
 CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,userId TEXT NOT NULL,expires INTEGER NOT NULL,csrf TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS docs(id TEXT PRIMARY KEY,kind TEXT NOT NULL,owner TEXT NOT NULL DEFAULT '',body TEXT NOT NULL);
 CREATE INDEX IF NOT EXISTS docs_scope ON docs(kind,owner);
 CREATE TABLE IF NOT EXISTS files(id TEXT PRIMARY KEY,owner TEXT NOT NULL,mime TEXT NOT NULL,body BLOB NOT NULL);
 CREATE TABLE IF NOT EXISTS devices(id TEXT PRIMARY KEY,userId TEXT NOT NULL,kind TEXT NOT NULL,body TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS delivery(id TEXT PRIMARY KEY,deviceId TEXT NOT NULL,noticeId TEXT NOT NULL,body TEXT NOT NULL,attempts INTEGER DEFAULT 0,nextAt INTEGER DEFAULT 0,status TEXT DEFAULT 'pending',error TEXT DEFAULT '');
 CREATE TABLE IF NOT EXISTS config(key TEXT PRIMARY KEY,value TEXT NOT NULL);`);
 if(!db.prepare('PRAGMA table_info(users)').all().some(c=>c.name==='active'))db.exec('ALTER TABLE users ADD COLUMN active INTEGER NOT NULL DEFAULT 1');
 let stateRows=null;
 const all=(kind,owner)=>stateRows?(stateRows.get(kind)||[]).filter(r=>owner===undefined||r.owner===owner).map(r=>r.value):db.prepare('SELECT body FROM docs WHERE kind=?'+(owner===undefined?'':' AND owner=?')+' ORDER BY rowid DESC').all(...(owner===undefined?[kind]:[kind,owner])).map(r=>JSON.parse(r.body));
 const get=(kind,key)=>{const r=db.prepare('SELECT body FROM docs WHERE kind=? AND id=?').get(kind,key);if(!r)fail(404,'No encontrado.');return JSON.parse(r.body);};
 const put=(kind,owner,body)=>{db.prepare('INSERT INTO docs(id,kind,owner,body) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body,owner=excluded.owner').run(body.id,kind,owner,JSON.stringify(body));return body;};
 const transaction=fn=>{db.exec('BEGIN IMMEDIATE');try{const value=fn();db.exec('COMMIT');return value;}catch(e){db.exec('ROLLBACK');throw e;}};
 const userView=u=>u?{id:u.id,email:u.email,name:u.name,phone:u.phone,town:u.town,role:u.role,sound:!!u.sound}:null;
 const passwordHash=p=>{const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(p,salt,64).toString('hex');};
 const addUser=(email,password,name,role='client')=>{if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8||password.length>200||!name)fail(400,'Ingresá nombre, correo válido y contraseña de al menos 8 caracteres.');if(db.prepare('SELECT id FROM users WHERE email=?').get(email))fail(409,'No se pudo crear la cuenta con esos datos.');const key=id();db.prepare('INSERT INTO users(id,email,name,phone,town,role,password) VALUES(?,?,?,?,?,?,?)').run(key,email,name,'','',role,passwordHash(password));return db.prepare('SELECT * FROM users WHERE id=?').get(key);};
 const notify=(userId,title,body,url='/#avisos',priority='normal')=>{const n=put('notice',userId,{id:id(),userId,title,body,url,priority,read:false,date:now()});for(const d of db.prepare('SELECT id FROM devices WHERE userId=?').all(userId)){db.prepare('INSERT INTO delivery(id,deviceId,noticeId,body) VALUES(?,?,?,?)').run(id(),d.id,n.id,JSON.stringify({title:priority==='urgent'?'URGENTE · AMC':['Tu presupuesto espera una respuesta','Último recordatorio de tu presupuesto','Venció el plazo del presupuesto'].includes(title)?title:'AMC Construcciones y Arreglos',body:priority==='urgent'?'Tenés una asignación urgente. Confirmá la recepción en AMC.':['Tu presupuesto espera una respuesta','Último recordatorio de tu presupuesto','Venció el plazo del presupuesto'].includes(title)?'Abrí AMC para revisar el plazo y responder.':'Tenés una nueva novedad. Abrí AMC para verla.',priority,url,id:n.id}));}if(priority==='urgent')queueMicrotask(()=>flushPush());return n;};
 const notifyAdmins=(title,body,url='/#admin')=>db.prepare("SELECT id FROM users WHERE role='admin'").all().forEach(u=>notify(u.id,title,body,url));
 const own=(u,r)=>{if(u.role!=='admin'&&r.userId!==u.id)fail(404,'No encontrado.');return r;};
 const requireAdmin=u=>{if(u.role!=='admin')fail(403,'Este acceso es exclusivo de AMC.');};
 const keys=pushKeys(db);
 if(demo&&!db.prepare("SELECT id FROM users WHERE email='admin@amc.test'").get()){
  addUser('admin@amc.test','AMC-Prueba-2026!','Ariel · AMC','admin');addUser('cliente@amc.test','Cliente-Prueba-2026!','Cliente de prueba');
  put('post','',{id:id(),title:'Inspiración para tu próximo proyecto',service:'Reparaciones',town:'Imagen ilustrativa',date:now(),description:'Publicación de ejemplo. Desde el panel podés subir tus propios trabajos.',image:'/assets/living.jpg',before:null,demo:true});
 }
 if(process.env.AMC_ADMIN_EMAIL&&process.env.AMC_ADMIN_PASSWORD&&!db.prepare("SELECT id FROM users WHERE role='admin'").get())addUser(process.env.AMC_ADMIN_EMAIL.toLowerCase(),process.env.AMC_ADMIN_PASSWORD,'AMC','admin');
 const send=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));};
 const readBody=async req=>{let chunks=[],size=0;for await(const chunk of req){size+=chunk.length;if(size>7*1024*1024)fail(413,'El archivo es demasiado grande.');chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}');}catch{fail(400,'Datos inválidos.');}};
 const rate=new Map();
 const checkRate=(key,limit)=>{const t=Date.now(),r=rate.get(key)||{count:0,end:t+900000};if(r.end<t){r.count=0;r.end=t+900000;}r.count++;rate.set(key,r);if(r.count>limit)fail(429,'Demasiados intentos. Probá en unos minutos.');if(rate.size>10000)for(const [k,v]of rate)if(v.end<t)rate.delete(k);};
 const safeFile=(user,key,mime)=>{const f=db.prepare('SELECT owner,mime FROM files WHERE id=?').get(key);if(!f||f.owner!==user.id||(mime&&!f.mime.startsWith(mime)))fail(400,'Archivo inválido o sin acceso.');return '/media/'+key;};
 const planning=planningFeatures({db,all,get,put,transaction,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,validDate,now,id,sha});
 const lifecycle=quoteLifecycle({all,put,transaction,notify,notifyAdmins,clock});
 const recovery=recoveryFeatures({db,all,put,transaction,requireAdmin,notifyAdmins,send,fail,text,sha,passwordHash,origin,clock,sendRecovery});
 const closure=closureFeatures({all,get,put,transaction,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,now,id,sha});
 const fieldwork=fieldworkFeatures({all,get,put,transaction,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,validDate,now,id,sha});
 const team=teamFeatures({db,all,get,put,transaction,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,amount,validDate,now,id,sha,addUser,passwordHash});
 const clientChatIds=user=>{const finished=new Set(all('work',user.id).filter(w=>w.status==='Finalizado').map(w=>w.quoteId)),seen=new Set();return new Set(all('quote',user.id).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).filter(q=>{if(seen.has(q.requestId))return false;seen.add(q.requestId);return Number(q.total)>0&&['Enviado','Cambios solicitados','Aceptado'].includes(q.status)&&!finished.has(q.id);}).map(q=>q.requestId));};
 const chatIds=user=>new Set(all('assignment',user.id).filter(t=>!['Cancelada','Finalizada'].includes(t.status)).map(t=>t.requestId));
 const chatOwn=(user,r)=>{if(user.role==='client')own(user,r);if(user.role==='client'&&!clientChatIds(user).has(r.id))fail(403,'La conversación está disponible mientras tu presupuesto o trabajo está en curso.');if(user.role==='employee'){if(!chatIds(user).has(r.id))fail(404,'Conversación no encontrada.');return r;}return own(user,r);};
 const chatState=user=>{const ids=chatIds(user);return {chatRequests:all('request').filter(r=>ids.has(r.id)).map(r=>({id:r.id,name:r.name,service:r.service,town:r.town})),messages:all('message').filter(m=>ids.has(m.requestId))};};
 const chatMedia=(user,p)=>{if(user.role!=='employee')return false;const ids=chatIds(user);return all('message').some(m=>ids.has(m.requestId)&&m.photos?.includes(p));};
 const handleFeature=featureRoutes({db,all,get,put,transaction,own,chatOwn,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,amount,validDate,now,id,sha});
 async function handle(req,res){
  if(origin.startsWith('https:'))res.setHeader('Strict-Transport-Security','max-age=31536000');res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','SAMEORIGIN');
  const url=new URL(req.url,origin),p=url.pathname,method=req.method;
  if(['GET','HEAD'].includes(method)&&(p==='/'||/\.(?:js|css|png|jpg|webp|svg|webmanifest|html|txt|xml)$/.test(p))&&!p.startsWith('/api/')&&!p.startsWith('/media/')){const file=path.resolve(ROOT,'public','.'+(p==='/'?'/index.html':p));if(!file.startsWith(path.join(ROOT,'public')+path.sep))return send(res,404,{error:'No encontrado.'});try{return staticResponse(req,res,file);}catch{return send(res,404,{error:'No encontrado.'});}}
  const cookie=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('amc_session='))?.slice(12);
  const session=cookie?db.prepare('SELECT * FROM sessions WHERE token=? AND expires>?').get(sha(cookie),Date.now()):null;
  const user=session?db.prepare('SELECT * FROM users WHERE id=? AND active=1').get(session.userId):null;
  try{
   if(!['GET','HEAD'].includes(method)){if(req.headers.origin!==origin)fail(403,'Origen no permitido.');if(!['/api/login','/api/register','/api/forgot-password','/api/reset-password'].includes(p)&&(!session||req.headers['x-csrf-token']!==session.csrf))fail(403,'Sesión vencida. Volvé a ingresar.');}
   if(['/api/forgot-password','/api/reset-password'].includes(p)){if(method!=='POST')fail(405,'Método no permitido.');checkRate(req.socket.remoteAddress+':recovery',8);const b=await readBody(req);if(await recovery.route({p,method,b,user,res}))return;}
   if(p==='/healthz'&&method==='GET'){db.prepare('SELECT 1 AS ok').get();return send(res,200,{ok:true});}
   if(p==='/api/config')return send(res,200,{demo,webPushKey:keys.publicKey,services});
   if(p==='/api/login'||p==='/api/register'){
    if(method!=='POST')fail(405,'Método no permitido.');checkRate(req.socket.remoteAddress+':login',30);const b=await readBody(req),email=text(b.email).toLowerCase(),password=typeof b.password==='string'?b.password:'';if(password.length>200)fail(400,'Contraseña inválida.');let u;
    if(p.endsWith('register')){checkRate(req.socket.remoteAddress+':register',8);u=addUser(email,password,text(b.name));}else{u=db.prepare('SELECT * FROM users WHERE email=?').get(email);const [salt,expected]=(u?.password||passwordHash('dummy-password')).split(':');if(!timingSafeEqual(Buffer.from(expected,'hex'),scryptSync(password,salt,64))||!u||!u.active)fail(401,'Correo o contraseña incorrectos.');}
    const raw=randomBytes(32).toString('hex'),csrf=randomBytes(24).toString('hex');db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(sha(raw),u.id,Date.now()+7*86400000,csrf);res.setHeader('Set-Cookie',`amc_session=${raw}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${origin.startsWith('https:')?'; Secure':''}`);return send(res,200,{user:userView(u),csrf});
   }
   if(p==='/api/state'&&method==='GET'){
    lifecycle.run();
    stateRows=new Map();for(const row of db.prepare("SELECT kind,owner,body FROM docs WHERE kind!='estimator' ORDER BY rowid DESC").all()){if(!stateRows.has(row.kind))stateRows.set(row.kind,[]);stateRows.get(row.kind).push({owner:row.owner,value:JSON.parse(row.body)});}try{
    const common={user:userView(user),csrf:session?.csrf,appearance:planning.appearance(),posts:all('post').filter(p=>!p.demo),reviews:all('review').filter(r=>r.approved),services};if(!user)return send(res,200,common);
    if(user.role==='employee')return send(res,200,{...common,...team.state(user),...fieldwork.state(user),...recovery.state(user),...closure.state(user),...planning.state(user),notices:all('notice',user.id),...chatState(user),appointments:[],extras:[],receipts:[],favorites:[],requests:[],quotes:[],works:[],referrals:[],clients:[],pendingReviews:[]});
    const owner=user.role==='admin'?undefined:user.id,allowedChat=user.role==='client'?clientChatIds(user):null;return send(res,200,{...common,archivedClients:user.role==='admin'?all('clientArchive').filter(c=>c.archived).map(c=>c.userId):[],offlineNotes:user.role==='admin'?all('offlineNote',user.id):[],...team.state(user),...fieldwork.state(user),...recovery.state(user),...closure.state(user),...planning.state(user),chatRequests:user.role==='client'?all('request',owner).filter(r=>allowedChat.has(r.id)):undefined,messages:all('message',owner).filter(m=>!allowedChat||allowedChat.has(m.requestId)),appointments:all('appointment',owner),extras:all('extra',owner),receipts:all('receipt',owner),favorites:all('favorite',user.id).map(r=>r.postId),requests:all('request',owner),quotes:all('quote',owner),works:all('work',owner),notices:all('notice',user.id),referrals:all('referral',user.id),clients:user.role==='admin'?db.prepare("SELECT id,name,email,phone,town FROM users WHERE role='client'").all():[],pendingReviews:user.role==='admin'?all('review').filter(r=>!r.approved):[]});}finally{stateRows=null;}
   }
   if(p==='/media/'+p.split('/')[2]&&p.startsWith('/media/')&&method==='GET'){
    const key=p.split('/')[2],file=db.prepare('SELECT id,owner,mime FROM files WHERE id=?').get(key);if(!file)fail(404,'Archivo no encontrado.');const publicFile=planning.publicMedia(p)||all('post').filter(x=>!x.demo).some(x=>x.image===p||x.before===p);
    const authorized=user&&(user.role==='admin'||file.owner===user.id||chatMedia(user,p)||team.media(user,p)||fieldwork.media(user,p)||closure.media(user,p)||all('request',user.id).some(x=>x.photos?.includes(p))||all('quote',user.id).some(x=>x.pdf===p)||all('work',user.id).some(x=>x.updates?.some(u=>u.image===p))||all('message',user.id).some(x=>(user.role!=='client'||clientChatIds(user).has(x.requestId))&&x.photos?.includes(p))||all('receipt',user.id).some(x=>x.file===p));if(!publicFile&&!authorized)fail(404,'Archivo no encontrado.');const mini=new URL(req.url,'http://localhost').searchParams.has('thumb')&&file.mime.startsWith('image/')?db.prepare('SELECT body FROM files WHERE id=?').get(key+'-thumb'):null;const tag=key+(mini?'-thumb':'');res.setHeader('Cache-Control','private, no-cache');res.setHeader('ETag','"'+tag+'"');if(req.headers['if-none-match']==='"'+tag+'"'){res.writeHead(304);return res.end();}res.setHeader('Content-Type',mini?'image/jpeg':file.mime);if(file.mime==='application/pdf')res.setHeader('Content-Disposition','attachment; filename="Documento-AMC.pdf"');return res.end(mini?.body||db.prepare('SELECT body FROM files WHERE id=?').get(key).body);
   }
   if(p.startsWith('/api/')){
    if(!user)fail(401,'Ingresá a tu cuenta para continuar.');checkRate(user.id+':api',400);if(method==='GET'&&/^\/api\/requests\/[^/]+\/messages$/.test(p)){const request=chatOwn(user,get('request',p.split('/')[3]));const messages=all('message',request.userId).filter(m=>m.requestId===request.id).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));const after=url.searchParams.get('after'),index=messages.findIndex(m=>m.id===after);return send(res,200,{messages:index>=0?messages.filter(m=>m.id!==after&&m.date>=messages[index].date):messages});}const b=await readBody(req);
    if(user.role==='employee'&&!['/api/logout','/api/profile','/api/upload','/api/devices','/api/notices/read','/api/notices/test'].includes(p)&&!/^\/api\/requests\/[^/]+\/messages$/.test(p)&&!/^\/api\/assignments\/[^/]+\/(report|visit-sheet|materials)$/.test(p))fail(403,'Tu acceso está limitado a tus asignaciones.');
    if(method==='POST'&&(p==='/api/assignments'||/^\/api\/assignments\/[^/]+\/edit$/.test(p)))planning.validateTime(b.day,b.time);
    if(method==='POST'&&/^\/api\/requests\/[^/]+\/appointment$/.test(p))planning.validateTime(b.day,b.time,Number(b.duration));
    if(p==='/api/offline-notes'&&method==='POST'){requireAdmin(user);if(!/^[\w-]{8,100}$/.test(b.idempotencyKey||'')||!text(b.text,4000)||!Array.isArray(b.photos)||b.photos.length>4)fail(400,'Informe inválido.');const key='offline-note-'+sha(user.id+':'+b.idempotencyKey),old=all('offlineNote',user.id).find(x=>x.id===key);if(old)return send(res,200,old);const task=get('assignment',b.assignmentId);if(['Cancelada','Finalizada'].includes(task.status))fail(409,'La asignación ya terminó o fue cancelada.');const photos=b.photos.map(x=>safeFile(user,x,'image/'));return send(res,201,put('offlineNote',user.id,{id:key,assignmentId:task.id,title:task.clientName+' · '+task.day,text:text(b.text,4000),photos,date:now()}));}
    if(p==='/api/estimator-state'&&method==='POST'){requireAdmin(user);const old=all('estimator',user.id)[0];if(b.revision!==(old?.revision||0))fail(409,'Hay cambios guardados desde otra ventana. Descargá tu copia antes de recargar.');if(!b.db||typeof b.db!=='object'||!Array.isArray(b.db.quotes)||!Array.isArray(b.db.customTariffs)||!b.draft||typeof b.draft!=='object'||!Array.isArray(b.draft.items))fail(400,'Datos del cotizador inválidos.');const saved=put('estimator',user.id,{id:'estimator-'+user.id,revision:(old?.revision||0)+1,db:b.db,draft:b.draft,updatedAt:now()});return send(res,200,{revision:saved.revision,updatedAt:saved.updatedAt});}
    if(await planning.route({p,method,b,user,res}))return;
    if(await recovery.route({p,method,b,user,res}))return;
    if(await closure.route({p,method,b,user,res}))return;
    if(await fieldwork.route({p,method,b,user,res}))return;
    if(await team.route({p,method,b,user,res}))return;
    if(await handleFeature({p,method,b,user,res}))return;
    if(method==='POST'&&/^\/api\/clients\/[^/]+\/archive$/.test(p)){requireAdmin(user);const clientId=p.split('/')[3],client=db.prepare("SELECT id FROM users WHERE id=? AND role='client'").get(clientId);if(!client)fail(404,'Cliente no encontrado.');if(typeof b.archived!=='boolean')fail(400,'Acción inválida.');if(b.archived){const ws=all('work',clientId),qs=all('quote',clientId),finished=new Set(ws.filter(w=>w.status==='Finalizado').map(w=>qs.find(q=>q.id===w.quoteId)?.requestId));if(all('request',clientId).some(r=>r.status!=='Cerrada'&&!finished.has(r.id))||ws.some(w=>w.status!=='Finalizado'||w.budget-(w.payments||[]).reduce((n,p)=>n+p.amount,0)>0))fail(409,'Tiene pedidos abiertos, una obra pendiente o saldo por cobrar.');}put('clientArchive','',{id:'archive-'+clientId,userId:clientId,archived:b.archived});return send(res,200,{ok:true});}
    if(method==='POST'&&p==='/api/logout'){db.prepare('DELETE FROM sessions WHERE token=?').run(session.token);db.prepare('DELETE FROM devices WHERE userId=? AND id=?').run(user.id,text(b.deviceId));res.setHeader('Set-Cookie','amc_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return send(res,200,{ok:true});}
    if(method==='POST'&&p==='/api/profile'){if(!text(b.name))fail(400,'El nombre es obligatorio.');db.prepare('UPDATE users SET name=?,phone=?,town=?,sound=? WHERE id=?').run(text(b.name),text(b.phone),text(b.town),b.sound?1:0,user.id);return send(res,200,{ok:true});}
    if(method==='POST'&&p==='/api/upload'){
     const mime=text(b.mime),bytes=Buffer.from(text(b.base64,9e6),'base64');const valid=(mime==='image/jpeg'&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255)||(mime==='image/png'&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))||(mime==='image/webp'&&bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP')||(mime==='application/pdf'&&bytes.toString('ascii',0,5)==='%PDF-');if(!valid||bytes.length>5*1024*1024)fail(400,'Usá una foto o un PDF válido de hasta 5 MB.');const miniature=b.thumbnail?Buffer.from(text(b.thumbnail,180000),'base64'):null;if(miniature&&(!mime.startsWith('image/')||miniature.length>128000||miniature[0]!==255||miniature[1]!==216||miniature[2]!==255))fail(400,'Miniatura inválida.');const storedSize=bytes.length+(miniature?.length||0);const totalStored=db.prepare('SELECT coalesce(sum(length(body)),0) AS total FROM files').get().total;if(totalStored+storedSize>150*1024*1024)fail(413,'El almacenamiento de archivos de la prueba está completo. AMC debe ampliar o revisar el espacio.');const used=db.prepare('SELECT coalesce(sum(length(body)),0) AS total FROM files WHERE owner=?').get(user.id).total;if(used+storedSize>100*1024*1024)fail(413,'Alcanzaste el límite de archivos de esta versión.');const key=id();transaction(()=>{db.prepare('INSERT INTO files VALUES(?,?,?,?)').run(key,user.id,mime,bytes);if(miniature)db.prepare('INSERT INTO files VALUES(?,?,?,?)').run(key+'-thumb',user.id,'image/jpeg',miniature);});return send(res,201,{id:key,url:'/media/'+key});
    }
    if(method==='POST'&&p==='/api/favorites'){get('post',b.postId);const key=user.id+':'+b.postId;const old=db.prepare('SELECT id FROM docs WHERE id=?').get(key);if(old)db.prepare('DELETE FROM docs WHERE id=?').run(key);else put('favorite',user.id,{id:key,postId:b.postId});return send(res,200,{ok:true});}
    if(method==='POST'&&p==='/api/requests'){
     if(user.role!=='client')fail(400,'Usá una cuenta de cliente para crear pedidos.');if(!text(b.name)||!text(b.town)||!text(b.phone)||!text(b.description)||!services.includes(b.service)||!['presupuesto','visita'].includes(b.type))fail(400,'Completá el pedido y tus datos de contacto.');if(b.type==='visita')planning.validateTime(b.day,b.slot==='Mañana · 9 a 12'?'09:00':'14:00',b.slot==='Mañana · 9 a 12'?180:240);if(b.type==='visita'&&(!validDate(b.day)||b.day<now().slice(0,10)||!['Mañana · 9 a 12','Tarde · 14 a 18'].includes(b.slot)||!text(b.address)))fail(400,'Completá fecha, horario y dirección válidos.');if(b.postId)get('post',b.postId);const photos=(Array.isArray(b.photos)?b.photos:[]).slice(0,4).map(k=>safeFile(user,k,'image/'));
     const item=transaction(()=>{const r=put('request',user.id,{id:id(),userId:user.id,type:b.type,name:text(b.name),phone:text(b.phone),town:text(b.town),description:text(b.description,4000),service:b.service,dimensions:text(b.dimensions),day:text(b.day),slot:text(b.slot),address:text(b.address),postId:text(b.postId),photos,status:'Nueva',date:now()});notifyAdmins('Nueva solicitud',r.name+' · '+r.service);notify(user.id,'Recibimos tu solicitud','AMC revisará tu pedido.');return r;});return send(res,201,item);
    }
    if(method==='POST'&&/^\/api\/requests\/[^/]+\/status$/.test(p)){requireAdmin(user);const r=get('request',p.split('/')[3]);if(!['Nueva','En contacto','Visita confirmada','Presupuestada','Cerrada'].includes(b.status))fail(400,'Estado inválido.');transaction(()=>{put('request',r.userId,{...r,status:b.status});notify(r.userId,'Tu solicitud cambió de estado',b.status);});return send(res,200,{ok:true});}
    if(method==='POST'&&p==='/api/quotes'){
     lifecycle.run();
     requireAdmin(user);const r=get('request',b.requestId);if(!text(b.externalId))fail(400,'Guardá el presupuesto antes de enviarlo.');const version=text(b.version);if(!/^[a-f0-9]{64}$/.test(version))fail(400,'Versión inválida.');const key=sha(r.id+':'+b.externalId+':'+version);const existing=db.prepare("SELECT body FROM docs WHERE id=? AND kind='quote'").get(key);if(existing)return send(res,200,JSON.parse(existing.body));
     const items=(Array.isArray(b.items)?b.items:[]).slice(0,100).map(x=>({description:text(x.description,1500)}));if(!items.length||items.some(x=>!x.description))fail(400,'Agregá trabajos al presupuesto.');const total=amount(b.total),pdf=safeFile(user,b.pdfId,'application/pdf');if(all('quote',r.userId).some(q=>q.requestId===r.id&&q.status==='Aceptado'))fail(409,'Este pedido ya tiene un presupuesto aceptado.');
     const q=transaction(()=>{for(const prev of all('quote',r.userId).filter(q=>q.requestId===r.id&&q.status==='Enviado'))put('quote',r.userId,{...prev,status:'Reemplazado'});const q=put('quote',r.userId,{id:key,userId:r.userId,requestId:r.id,externalId:text(b.externalId),number:text(b.number),items,total,pdf,validity:'10',payment:text(b.payment,1500),notes:text(b.notes,4000),status:'Enviado',...lifecycle.terms()});put('request',r.userId,{...r,status:'Presupuestada'});notify(r.userId,'Tu presupuesto está listo','Tenés 10 días corridos desde este envío para aceptar, pedir cambios o rechazar.','/#presupuestos');return q;});return send(res,201,q);
    }
    if(method==='POST'&&/^\/api\/quotes\/[^/]+\/reply$/.test(p)){
     lifecycle.run();const q=own(user,get('quote',p.split('/')[3]));if(user.role!=='client')fail(403,'La respuesta corresponde al cliente.');if(!['Aceptado','Cambios solicitados','Rechazado'].includes(b.status))fail(400,'Respuesta inválida.');if(q.status===b.status)return send(res,200,{ok:true});if(q.status!=='Enviado')fail(409,q.status==='Vencido'?'Venció el plazo de 10 días. Escribile a AMC para revisar el presupuesto.':'Este presupuesto ya no admite esa respuesta.');if(b.status==='Cambios solicitados'&&!text(b.message))fail(400,'Contanos qué querés cambiar.');transaction(()=>{put('quote',user.id,{...q,status:b.status,reply:text(b.message,4000),repliedAt:now()});if(b.status==='Aceptado'){const r=get('request',q.requestId);put('request',user.id,{...r,status:'Presupuesto aceptado'});put('work',user.id,{id:'work-'+q.id,userId:user.id,quoteId:q.id,title:r.service,address:r.address||r.town,status:'Presupuesto aceptado',budget:q.total,payments:[],updates:[],start:'',end:''});}notifyAdmins('Respuesta a presupuesto',user.name+' · '+b.status);});return send(res,200,{ok:true});
    }
    if(method==='POST'&&/^\/api\/works\/[^/]+$/.test(p)){requireAdmin(user);const w=get('work',p.split('/')[3]);planning.validateWork(w,b.start||'',b.end||'');if(b.status==='Finalizado'&&w.status!=='Finalizado')fail(400,'Usá Cierre de obra para solicitar la conformidad del cliente.');const statuses=['Presupuesto aceptado','Trabajo programado','En ejecución','Finalizado'];if(!statuses.includes(b.status)||(b.start&&!validDate(b.start))||(b.end&&!validDate(b.end))||(b.start&&b.end&&b.end<b.start))fail(400,'Estado o fechas inválidas.');transaction(()=>{put('work',w.userId,{...w,status:b.status,start:b.start||'',end:b.end||''});notify(w.userId,'Actualización de tu obra','Revisá el estado y las fechas.','/#obra');});return send(res,200,{ok:true});}
    if(method==='POST'&&/^\/api\/works\/[^/]+\/payments$/.test(p)){requireAdmin(user);const w=get('work',p.split('/')[3]),key=text(b.idempotencyKey);if(!key)fail(400,'Falta la referencia del pago.');if(w.payments.some(x=>x.key===key))return send(res,200,{ok:true});const n=amount(b.amount);if(n>w.budget-w.payments.reduce((a,x)=>a+x.amount,0)+.001||!validDate(b.date)||!text(b.description))fail(400,'Revisá importe, fecha y concepto. El pago no puede superar el saldo.');transaction(()=>{put('work',w.userId,{...w,payments:[...w.payments,{id:id(),key,amount:n,date:b.date,description:text(b.description)}]});notify(w.userId,'Pago registrado','Actualizamos el saldo de tu obra.','/#obra');});return send(res,200,{ok:true});}
    if(method==='POST'&&/^\/api\/works\/[^/]+\/updates$/.test(p)){requireAdmin(user);const w=get('work',p.split('/')[3]),image=safeFile(user,b.photoId,'image/');if(!text(b.text))fail(400,'Describí el avance.');transaction(()=>{put('work',w.userId,{...w,updates:[{id:id(),image,text:text(b.text,4000),date:now()},...w.updates]});notify(w.userId,'Nuevo avance de tu obra','Hay una nueva foto para vos.','/#obra');});return send(res,201,{ok:true});}
    if(method==='POST'&&p==='/api/posts'){requireAdmin(user);if(!text(b.title)||!text(b.description)||!text(b.town)||!services.includes(b.service))fail(400,'Completá la publicación.');const image=safeFile(user,b.photoId,'image/'),before=b.beforeId?safeFile(user,b.beforeId,'image/'):null;const post=put('post','',{id:id(),title:text(b.title),description:text(b.description,4000),town:text(b.town),service:b.service,date:now(),image,before,demo:false});return send(res,201,post);}
    if(method==='DELETE'&&/^\/api\/posts\/[^/]+$/.test(p)){requireAdmin(user);db.prepare("DELETE FROM docs WHERE id=? AND kind='post'").run(p.split('/')[3]);return send(res,200,{ok:true});}
    if(method==='POST'&&p==='/api/reviews'){if(user.role!=='client'||!all('work',user.id).some(w=>w.status==='Finalizado'))fail(403,'Podés reseñar cuando finalice una obra tuya.');if(![1,2,3,4,5].includes(Number(b.rating))||text(b.text).length<10)fail(400,'Completá la calificación y al menos 10 caracteres.');put('review',user.id,{id:id(),userId:user.id,name:user.name,rating:Number(b.rating),text:text(b.text,1500),date:now(),approved:false});notifyAdmins('Nueva reseña','Hay una reseña pendiente de revisión.');return send(res,201,{ok:true});}
    if(method==='POST'&&/^\/api\/reviews\/[^/]+\/approve$/.test(p)){requireAdmin(user);const r=get('review',p.split('/')[3]);put('review',r.userId,{...r,approved:true});return send(res,200,{ok:true});}
    if(method==='POST'&&p==='/api/referrals'){if(!text(b.name))fail(400,'Ingresá un nombre.');put('referral',user.id,{id:id(),name:text(b.name),note:text(b.note,1000),date:now()});return send(res,201,{ok:true});}
    if(method==='POST'&&p==='/api/notices/read'){for(const n of all('notice',user.id).filter(n=>!n.read&&(!b.id||n.id===b.id)))put('notice',user.id,{...n,read:true});return send(res,200,{ok:true});}
    if(method==='POST'&&p==='/api/notices/test'){notify(user.id,'Notificación de prueba','Si habilitaste los avisos, revisá tu dispositivo.');return send(res,201,{ok:true});}
    if(method==='POST'&&p==='/api/notices'){requireAdmin(user);const recipient=db.prepare("SELECT id FROM users WHERE id=? AND role='client'").get(b.userId);if(!recipient||!text(b.title)||!text(b.body))fail(400,'Elegí cliente, título y mensaje.');notify(recipient.id,text(b.title),text(b.body,2000));return send(res,201,{ok:true});}
    if(method==='POST'&&p==='/api/devices'){if(!['web','android'].includes(b.kind)||!validSubscription(b.kind,b.subscription))fail(400,'Suscripción inválida.');const body=JSON.stringify(b.subscription),key=sha(b.kind+':'+(b.kind==='web'?b.subscription.endpoint:b.subscription.token));if(db.prepare('SELECT count(*) AS n FROM devices WHERE userId=?').get(user.id).n>=20&&!db.prepare('SELECT id FROM devices WHERE id=?').get(key))fail(400,'Límite de dispositivos alcanzado.');transaction(()=>{db.prepare('DELETE FROM delivery WHERE deviceId=?').run(key);db.prepare('INSERT INTO devices VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET userId=excluded.userId,body=excluded.body').run(key,user.id,b.kind,body);});return send(res,200,{deviceId:key});}
    fail(404,'Acción no encontrada.');
   }
   if(method!=='GET'&&method!=='HEAD')fail(405,'Método no permitido.');
   if(p==='/presupuestos'){if(!user){res.writeHead(302,{Location:'/#ingresar'});return res.end();}requireAdmin(user);let html=readFileSync(path.join(ROOT,'private/presupuestos-original.html'),'utf8');const saved=all('estimator',user.id)[0]||null;const bootstrap=JSON.stringify({saved,csrf:session.csrf}).replaceAll('<','\\u003c');html=html.replace('<head>','<head><script>window.AMCStored='+bootstrap+';</script>');html=html.replace('</body>','<script src="/estimator-sync.js"></script><script src="/presupuestos-bridge.js"></script><script src="/estimator-steps.js"></script></body>');res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(html);}
   const file=path.resolve(ROOT,'public','.'+(p==='/'?'/index.html':p));if(!file.startsWith(path.join(ROOT,'public')+path.sep))fail(404,'No encontrado.');try{const bytes=readFileSync(file);res.setHeader('Content-Type',({'html':'text/html; charset=utf-8','js':'text/javascript; charset=utf-8','css':'text/css; charset=utf-8','jpg':'image/jpeg','png':'image/png','svg':'image/svg+xml','webmanifest':'application/manifest+json'})[file.split('.').pop()]||'application/octet-stream');res.end(method==='HEAD'?undefined:bytes);}catch{fail(404,'No encontrado.');}
  }catch(e){if(!res.headersSent)send(res,e.status||500,{error:e.status?e.message:'Ocurrió un error. Intentá nuevamente.'});else res.end();}
 }
 let delivering=false;
 async function flushPush(){if(delivering)return;delivering=true;try{for(const row of db.prepare("SELECT delivery.*,devices.kind,devices.body AS device,devices.userId FROM delivery JOIN devices ON devices.id=delivery.deviceId WHERE status='pending' AND nextAt<=? ORDER BY CASE WHEN json_extract(delivery.body,'$.priority')='urgent' THEN 0 ELSE 1 END, delivery.rowid LIMIT 20").all(Date.now())){try{const u=db.prepare('SELECT sound FROM users WHERE id=?').get(row.userId);await deliver(row.kind,JSON.parse(row.device),JSON.parse(row.body),keys,!!u?.sound);db.prepare("UPDATE delivery SET status='sent',error='' WHERE id=?").run(row.id);}catch(e){const attempts=row.attempts+1;db.prepare('UPDATE delivery SET attempts=?,status=?,nextAt=?,error=? WHERE id=?').run(attempts,e.gone?'expired':attempts>=6?'failed':'pending',Date.now()+Math.min(3600000,30000*2**attempts),text(e.message,300),row.id);if(e.gone)db.prepare('DELETE FROM devices WHERE id=?').run(row.deviceId);}}}finally{delivering=false;}}
 const server=http.createServer((req,res)=>{handle(req,res).catch(()=>{if(!res.headersSent)send(res,503,{error:'No pudimos confirmar la operación. Revisá la conexión y el estado antes de repetirla.'});else res.end();});});server.requestTimeout=30000;server.headersTimeout=10000;const timer=setInterval(()=>flushPush().catch(()=>console.error('No se pudo procesar la cola de avisos.')),5000);timer.unref();const quoteTimer=setInterval(()=>{try{lifecycle.run();}catch{console.error('No se pudo revisar el plazo de presupuestos.');}},60000);quoteTimer.unref();server.on('close',()=>{clearInterval(timer);clearInterval(quoteTimer);db.close();});return {server,db,addUser,flushPush,processQuotes:lifecycle.run};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const demo=process.argv.includes('--demo'),port=Number(process.env.PORT||4180),origin=process.env.AMC_ORIGIN||process.env.RENDER_EXTERNAL_URL||`http://localhost:${port}`;
 if(!demo&&(!origin.startsWith('https:'))){console.error('Producción requiere AMC_ORIGIN=https://tu-dominio. Para prueba local usá node server.mjs --demo.');process.exit(1);}
 if(process.env.RENDER&&!process.env.AMC_DATABASE_URL){console.error('Render requiere AMC_DATABASE_URL: no se permite guardar en disco temporal.');process.exit(1);}
 const app=createApp({demo,origin,dbPath:process.env.AMC_DB_PATH||path.join(ROOT,'data',demo?'demo.sqlite':'amc.sqlite')});app.server.listen(port,demo?'127.0.0.1':'0.0.0.0',()=>console.log('AMC conectado: '+origin+(demo?' · prueba local, cuentas de ejemplo':' ')));
}
