import {staticResponse} from './static-response.mjs';
import {planningFeatures} from './planning.mjs';
import {recoveryFeatures} from './recovery.mjs';
import {closureFeatures} from './closure.mjs';
import {fieldworkFeatures} from './fieldwork.mjs';
import {quoteLifecycle} from './quote-lifecycle.mjs';
import {twoFactorFeatures} from './twofactor.mjs';
import {authRoutes} from './auth-routes.mjs';
import {createAuthCore} from './auth-core.mjs';
import {chatFeatures} from './chat-core.mjs';
import {clientRequestFeatures} from './client-requests.mjs';
import {notificationFeatures} from './notifications.mjs';
import {mediaStorageFeatures} from './media-storage.mjs';
import {mediaAccessFeatures} from './media-access.mjs';
import {createMediaUploadParser} from './media-upload-parser.mjs';
import {createSupabaseFileStore} from './storage-supabase.mjs';
import {createSystemHealth} from './system-health.mjs';
import {createDatabaseCore} from './database-core.mjs';
import http from 'node:http';
import {teamFeatures} from './team.mjs';
import {featureRoutes} from './features.mjs';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {pushKeys,deliver,validSubscription} from './push.mjs';
const ROOT=path.dirname(fileURLToPath(import.meta.url));
export const services=['Albañilería','Revoques','Cerámicos y porcelanato','Pintura','Plomería','Electricidad','Reparaciones'];
export const serviceCatalog={Albañilería:['Revoque fino','Revoque completo','Porcelanato','Cerámicos','Contrapiso','Reparación de grietas'],Pintura:['Interior','Exterior','Aberturas'],Plomería:['Canillas','Inodoro','Termotanque','Pérdidas y cañerías'],Electricidad:['Iluminación','Tomacorrientes','Tablero eléctrico'],Reparaciones:['Humedad','Techos','Arreglos generales']};
const now=()=>new Date().toISOString(),id=()=>randomUUID(),sha=v=>createHash('sha256').update(v).digest('hex');
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const text=(v,max=200)=>typeof v==='string'?v.trim().slice(0,max):'';
const amount=v=>{if(!Number.isFinite(Number(v))||Number(v)<=0||Number(v)>1e10)fail(400,'Importe inválido.');return Math.round(Number(v)*100)/100;};
const optionalAmount=v=>{if(!Number.isFinite(Number(v||0))||Number(v||0)<0||Number(v||0)>1e10)fail(400,'Importe inválido.');return Math.round(Number(v||0)*100)/100;};
const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(v||'')&&!isNaN(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
export function createApp({dbPath=path.join(ROOT,'data/amc.sqlite'),demo=false,origin='http://localhost:4180',clock=Date.now,sendRecovery,twoFactorKey=process.env.AMC_2FA_KEY,fileStore}={}){
 const version=(process.env.RENDER_GIT_COMMIT||process.env.GITHUB_SHA||process.env.AMC_VERSION||'dev').slice(0,7),startedAt=Date.now();
 const recentServerErrors=[];const recentErrorCount=()=>{const cutoff=Date.now()-15*60*1000;while(recentServerErrors.length&&recentServerErrors[0]<cutoff)recentServerErrors.shift();return recentServerErrors.length;};
 const {db,remoteUrl,all,get,put,transaction,beginStateSnapshot,endStateSnapshot}=createDatabaseCore({dbPath,id,sha,now,fail});
 const objectStore=fileStore||createSupabaseFileStore();
 const {backupHealth,systemStatus}=createSystemHealth({db,version,remoteUrl,objectStore,recentErrorCount,startedAt});
 const {userView,passwordHash,addUser,own,requireAdmin,canAccessRequest,canAccessQuote,canAccessWork,requireResource,createAdminVerifier}=createAuthCore({db,all,id,fail});
 const publicWork=w=>{const {internalNotes,cost,internalCost,grossMargin,margin,journal,mobility,tools,contingency,calculations,estimatedTeam,personnelCost,actualPersonnelCost,actualOtherCosts,finalCost,realProfit,...safe}=w;return safe;};
 const publicQuote=q=>{const {cost,internalCost,grossMargin,margin,journal,mobility,tools,contingency,calculations,internalNotes,estimatedTeam,personnelCost,...safe}=q;return safe;};
 const employeeWork=w=>{const safe=publicWork(w);delete safe.budget;delete safe.payments;delete safe.baseBudget;delete safe.userId;return safe;};
 const keys=pushKeys(db);
 if(demo&&!db.prepare("SELECT id FROM users WHERE email='admin@amc.test'").get()){
  addUser('admin@amc.test','AMC-Prueba-2026!','Ariel · AMC','admin');addUser('cliente@amc.test','Cliente-Prueba-2026!','Cliente de prueba');
  put('post','',{id:id(),title:'Inspiración para tu próximo proyecto',service:'Reparaciones',town:'Imagen ilustrativa',date:now(),description:'Publicación de ejemplo. Desde el panel podés subir tus propios trabajos.',image:'/assets/living.jpg',before:null,demo:true});
 }
 if(process.env.AMC_ADMIN_EMAIL&&process.env.AMC_ADMIN_PASSWORD&&!db.prepare("SELECT id FROM users WHERE role='admin'").get())addUser(process.env.AMC_ADMIN_EMAIL.toLowerCase(),process.env.AMC_ADMIN_PASSWORD,'AMC','admin');
 const send=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));};
 const notifications=notificationFeatures({db,all,put,origin,now,id,schedulePush:()=>queueMicrotask(()=>flushPush()),send,requireAdmin,text,fail});
 const {notify,notifyAdmins,markNoticeRead,markNoticesForRoute,route:notificationRoutes}=notifications;
 const readRaw=async(req,limit=7*1024*1024)=>{let chunks=[],size=0;for await(const chunk of req){size+=chunk.length;if(size>limit)fail(413,'El archivo es demasiado grande.');chunks.push(chunk);}return Buffer.concat(chunks);};
 const readBody=async req=>{try{return JSON.parse((await readRaw(req)).toString()||'{}');}catch{fail(400,'Datos inválidos.');}};
 const readMultipart=createMediaUploadParser({readRaw,text,fail});
 const rate=new Map();
 const checkRate=(key,limit)=>{const t=Date.now(),r=rate.get(key)||{count:0,end:t+900000};if(r.end<t){r.count=0;r.end=t+900000;}r.count++;rate.set(key,r);if(r.count>limit)fail(429,'Demasiados intentos. Probá en unos minutos.');if(rate.size>10000)for(const [k,v]of rate)if(v.end<t)rate.delete(k);};
 const verifyAdmin=createAdminVerifier(checkRate);
 const mediaStorage=mediaStorageFeatures({db,all,put,transaction,objectStore,text,fail,id,now});
 const {safeFile,cleanupOrphanFiles}=mediaStorage;
 const planning=planningFeatures({db,all,get,put,transaction,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,validDate,now,id,sha});
 const lifecycle=quoteLifecycle({all,put,transaction,notify,notifyAdmins,clock});
 const twoFactor=twoFactorFeatures({db,all,put,transaction,requireAdmin,verifyAdmin,send,fail,now,keyValue:twoFactorKey});
 const authentication=authRoutes({db,addUser,userView,passwordHash,twoFactor,checkRate,rate,text,sha,send,fail,origin,readBody});
 const recovery=recoveryFeatures({db,all,put,transaction,requireAdmin,verifyAdmin,notifyAdmins,send,fail,text,sha,passwordHash,origin,clock,sendRecovery});
 const closure=closureFeatures({db,all,get,put,transaction,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,now,id,sha});
 const fieldwork=fieldworkFeatures({all,get,put,transaction,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,validDate,now,id,sha});
 const team=teamFeatures({db,all,get,put,transaction,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,amount,validDate,now,id,sha,addUser,passwordHash,planning});
 const chat=chatFeatures({db,all,get,put,own,safeFile,notify,notifyAdmins,send,fail,text,now,sha,markNoticesForRoute});
 const {clientChatIds,chatOwn,chatSummary,staffMessages,staffUnread,staffReadByEmployee,staffReadByAdmin}=chat;
 const mediaAccess=mediaAccessFeatures({db,all,objectStore,planning,team,fieldwork,closure,staffMessages,canAccessRequest,canAccessWork,clientChatIds,fail});
 const {canAccessPrivateFile}=mediaAccess;
 const clientRequests=clientRequestFeatures({db,all,get,put,transaction,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,validDate,now,id,services,serviceCatalog,planning});
 const handleFeature=featureRoutes({db,all,get,put,transaction,own,chatOwn,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,amount,validDate,now,id,sha,planning,markNoticesForRoute});
 async function handle(req,res){
  const url=new URL(req.url,origin),p=url.pathname,method=req.method,estimatorPage=p==='/presupuestos';
  if(origin.startsWith('https:'))res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');
  res.setHeader('Cache-Control','no-store');
  res.setHeader('X-Content-Type-Options','nosniff');
  res.setHeader('Referrer-Policy','same-origin');
  res.setHeader('X-Frame-Options','SAMEORIGIN');
  res.setHeader('Cross-Origin-Opener-Policy','same-origin-allow-popups');
  res.setHeader('Cross-Origin-Resource-Policy','same-origin');
  res.setHeader('Permissions-Policy','camera=(self), microphone=(), geolocation=(), payment=(), usb=(), serial=(), bluetooth=()');
  res.setHeader('Content-Security-Policy',estimatorPage?"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; frame-ancestors 'self'; frame-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; worker-src 'self'; manifest-src 'self'":"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; frame-ancestors 'self'; frame-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; worker-src 'self'; manifest-src 'self'");
  if(['GET','HEAD'].includes(method)&&(p==='/'||/\.(?:js|css|png|jpg|webp|svg|webmanifest|html|txt|xml)$/.test(p))&&!p.startsWith('/api/')&&!p.startsWith('/media/')){const file=path.resolve(ROOT,'public','.'+(p==='/'?'/index.html':p));if(!file.startsWith(path.join(ROOT,'public')+path.sep))return send(res,404,{error:'No encontrado.'});try{return staticResponse(req,res,file);}catch{return send(res,404,{error:'No encontrado.'});}}
  const {session,user}=authentication.resolve(req);
  try{
   if(!['GET','HEAD'].includes(method)){if(req.headers.origin!==origin)fail(403,'Origen no permitido.');if(!['/api/login','/api/register','/api/forgot-password','/api/reset-password'].includes(p)&&(!session||req.headers['x-csrf-token']!==session.csrf))fail(403,'Sesión vencida. Volvé a ingresar.');}
   if(['/api/forgot-password','/api/reset-password'].includes(p)){if(method!=='POST')fail(405,'Método no permitido.');checkRate(req.socket.remoteAddress+':recovery',8);const b=await readBody(req);if(await recovery.route({p,method,b,user,res}))return;}
   if((p==='/health'||p==='/healthz')&&method==='GET'){const before=Date.now();db.prepare('SELECT 1 AS ok').get();return send(res,200,{ok:true,database:'available',driver:remoteUrl?'postgresql':'sqlite',databaseMs:Date.now()-before,version,errors5xx15m:recentErrorCount(),...backupHealth(),uptimeSeconds:Math.floor((Date.now()-startedAt)/1000)});}
   if(p==='/api/config')return send(res,200,{demo,webPushKey:keys.publicKey,services,version});
   if(await authentication.handlePublic({p,method,req,res}))return;
   if(p==='/api/state'&&method==='GET'){
    lifecycle.run();
    const snapshotAll=user?.role==='admin';if(snapshotAll)beginStateSnapshot();try{
    const savedProfile=user?all('clientProfile',user.id)[0]:null,common={user:user?{...userView(user),address:savedProfile?.address||''}:null,...(user?chatSummary(user):{}),csrf:session?.csrf,appearance:planning.appearance(),posts:all('post').filter(p=>!p.demo),reviews:all('review').filter(r=>r.approved),myReview:user?.role==='client'?all('review',user.id)[0]||null:null,services,serviceCatalog};if(!user)return send(res,200,common);
    if(user.role==='employee')return send(res,200,{...common,...team.state(user),...fieldwork.state(user),...recovery.state(user),...closure.state(user),...planning.state(user),notices:all('notice',user.id),staffMessages:staffMessages(user),staffUnread:staffUnread(user),staffReadByAdmin:staffReadByAdmin(user.id),chatRequests:[],messages:[],appointments:[],extras:[],receipts:[],favorites:[],requests:[],quotes:[],works:all('work').filter(w=>canAccessWork(user,w)).map(employeeWork),referrals:[],clients:[],pendingReviews:[]});
    const leads=user.role==='admin'?all('leadClient'):[],registered=user.role==='admin'?db.prepare("SELECT id,name,email,phone,town,1 AS hasAccount FROM users WHERE role='client'").all().map(c=>{const profile=all('clientProfile',c.id)[0],adminNote=all('clientAdminNote').find(n=>n.clientId===c.id);return {...c,address:profile?.address||'',note:adminNote?.note||'',linkedLeadId:leads.find(l=>l.linkedUserId===c.id)?.id||null};}):[],linkedLeadIds=new Set(leads.filter(l=>l.linkedUserId).map(l=>l.id)),owner=user.role==='admin'?undefined:user.id,allowedChat=user.role==='client'?clientChatIds(user):null;return send(res,200,{...common,agendaClients:user.role==='admin'?[...registered,...leads.filter(x=>!linkedLeadIds.has(x.id)).map(x=>({...x,hasAccount:0}))]:[],archivedClients:user.role==='admin'?all('clientArchive').filter(c=>c.archived).map(c=>c.userId):[],offlineNotes:user.role==='admin'?all('offlineNote',user.id):[],staffMessages:user.role==='admin'?staffMessages(user):[],...team.state(user),...fieldwork.state(user),...recovery.state(user),...closure.state(user),...planning.state(user),chatRequests:user.role==='client'?all('request',owner).filter(r=>allowedChat.has(r.id)):undefined,messages:all('message',owner).filter(m=>!allowedChat||allowedChat.has(m.requestId)),appointments:all('appointment',owner),extras:all('extra',owner),receipts:all('receipt',owner),favorites:all('favorite',user.id).map(r=>r.postId),requests:all('request',owner),quotes:all('quote',owner).map(q=>user.role==='admin'?q:publicQuote(q)),works:all('work',owner).map(w=>user.role==='admin'?w:publicWork(w)),notices:all('notice',user.id),referrals:all('referral',user.id),clients:user.role==='admin'?registered:[],pendingReviews:user.role==='admin'?all('review').filter(r=>!r.approved):[],staffReadByEmployee:user.role==='admin'?staffReadByEmployee():undefined,system:user.role==='admin'?systemStatus():undefined,twoFactor:user.role==='admin'?twoFactor.status(user):undefined});}finally{if(snapshotAll)endStateSnapshot();}
   }
   if(await mediaAccess.serve({user,p,method,req,res}))return;
   if(p.startsWith('/api/')){
    if(!user)fail(401,'Ingresá a tu cuenta para continuar.');checkRate(user.id+':api',400);if(p.startsWith('/api/admin/2fa/')){const twoFactorBody=method==='GET'?{}:await readBody(req);if(await twoFactor.route({p,method,b:twoFactorBody,user,res,session}))return;}if(chat.routeBeforeBody({p,method,user,url,res}))return;const b=p==='/api/upload'&&String(req.headers['content-type']||'').startsWith('multipart/form-data')?await readMultipart(req):await readBody(req);
    if(chat.routeAfterBody({p,method,b,user,url,res}))return;
    if(user.role==='employee'&&/^\/api\/requests\/[^/]+\/messages(?:\/read)?$/.test(p))fail(404,'Conversación no encontrada.');
    if(user.role==='employee'&&!['/api/logout','/api/profile','/api/upload','/api/devices','/api/notices/read','/api/notices/test'].includes(p)&&!/^\/api\/assignments\/[^/]+\/(report|visit-sheet|materials)$/.test(p))fail(403,'Tu acceso está limitado a tus asignaciones.');
    if(method==='POST'&&(p==='/api/assignments'||/^\/api\/assignments\/[^/]+\/edit$/.test(p)))planning.validateTime(b.day,b.time);
    if(method==='POST'&&/^\/api\/requests\/[^/]+\/appointment$/.test(p))planning.validateTime(b.day,b.time,Number(b.duration));
    if(p==='/api/offline-notes'&&method==='POST'){requireAdmin(user);if(!/^[\w-]{8,100}$/.test(b.idempotencyKey||'')||!text(b.text,4000)||!Array.isArray(b.photos)||b.photos.length>4)fail(400,'Informe inválido.');const key='offline-note-'+sha(user.id+':'+b.idempotencyKey),old=all('offlineNote',user.id).find(x=>x.id===key);if(old)return send(res,200,old);const task=get('assignment',b.assignmentId);if(['Cancelada','Finalizada'].includes(task.status))fail(409,'La asignación ya terminó o fue cancelada.');const photos=b.photos.map(x=>safeFile(user,x,'image/'));return send(res,201,put('offlineNote',user.id,{id:key,assignmentId:task.id,title:task.clientName+' · '+task.day,text:text(b.text,4000),photos,date:now()}));}
    if(p==='/api/estimator-state'&&method==='POST'){requireAdmin(user);const old=all('estimator',user.id)[0];if(b.revision!==(old?.revision||0))fail(409,'Hay cambios guardados desde otra ventana. Descargá tu copia antes de recargar.');if(!b.db||typeof b.db!=='object'||!Array.isArray(b.db.quotes)||!Array.isArray(b.db.customTariffs)||!b.draft||typeof b.draft!=='object'||!Array.isArray(b.draft.items))fail(400,'Datos del cotizador inválidos.');const saved=put('estimator',user.id,{id:'estimator-'+user.id,revision:(old?.revision||0)+1,db:b.db,draft:b.draft,updatedAt:now()});return send(res,200,{revision:saved.revision,updatedAt:saved.updatedAt});}
    if(await planning.route({p,method,b,user,res}))return;
    if(await recovery.route({p,method,b,user,res}))return;
    if(await closure.route({p,method,b,user,res}))return;
    if(await fieldwork.route({p,method,b,user,res}))return;
    if(await team.route({p,method,b,user,res}))return;
    if(await handleFeature({p,method,b,user,res}))return;
    if(await clientRequests.route({p,method,b,user,res}))return;
    if(authentication.logout({p,method,user,session,b,res}))return;
    if(method==='POST'&&p==='/api/profile'){if(!text(b.name))fail(400,'El nombre es obligatorio.');db.prepare('UPDATE users SET name=?,phone=?,town=?,sound=? WHERE id=?').run(text(b.name),text(b.phone),text(b.town),b.sound?1:0,user.id);if(user.role==='client')put('clientProfile',user.id,{id:'profile-'+user.id,userId:user.id,address:text(b.address,500)});return send(res,200,{ok:true});}
    if(method==='POST'&&p==='/api/upload')return send(res,201,await mediaStorage.upload(user,b));
    if(method==='POST'&&p==='/api/favorites'){get('post',b.postId);const key=user.id+':'+b.postId;const old=db.prepare('SELECT id FROM docs WHERE id=?').get(key);if(old)db.prepare('DELETE FROM docs WHERE id=?').run(key);else put('favorite',user.id,{id:key,postId:b.postId});return send(res,200,{ok:true});}
    if(method==='POST'&&p==='/api/quotes'){
     lifecycle.run();
     requireAdmin(user);const r=get('request',b.requestId);if(!text(b.externalId))fail(400,'Guardá el presupuesto antes de enviarlo.');const version=text(b.version);if(!/^[a-f0-9]{64}$/.test(version))fail(400,'Versión inválida.');const key=sha(r.id+':'+b.externalId+':'+version);const existing=db.prepare("SELECT body FROM docs WHERE id=? AND kind='quote'").get(key);if(existing)return send(res,200,JSON.parse(existing.body));
     const items=(Array.isArray(b.items)?b.items:[]).slice(0,100).map(x=>({description:text(x.description,1500)}));if(!items.length||items.some(x=>!x.description))fail(400,'Agregá trabajos al presupuesto.');const total=amount(b.total),estimatedTeam=(Array.isArray(b.estimatedTeam)?b.estimatedTeam:[]).slice(0,20).map(x=>({employeeId:text(x.employeeId),manual:!x.employeeId,name:text(x.name),dailyCost:optionalAmount(x.dailyCost),days:Math.max(0,Number(x.days||0))})).filter(x=>x.employeeId||x.manual&&x.name),personnelCost=estimatedTeam.reduce((sum,x)=>sum+x.days*x.dailyCost,0),submittedInternalCost=b.internalCost===undefined?0:amount(b.internalCost),internalCost=Math.max(submittedInternalCost,personnelCost),grossMargin=total-internalCost,pdf=b.pdfId?safeFile(user,b.pdfId,'application/pdf'):'';const recipient=!r.leadId&&!!db.prepare("SELECT id FROM users WHERE id=? AND role='client'").get(r.userId),deliveryStatus=recipient?'Enviado':'Guardado';if(all('quote',r.userId).some(q=>q.requestId===r.id&&q.status==='Aceptado'))fail(409,'Este pedido ya tiene un presupuesto aceptado.');
     const q=transaction(()=>{for(const prev of all('quote',r.userId).filter(q=>q.requestId===r.id&&['Enviado','Guardado','Entregado','Cambios solicitados'].includes(q.status)))put('quote',r.userId,{...prev,status:'Reemplazado',replacedAt:now()});const q=put('quote',r.userId,{id:key,presupuestoId:key,solicitudId:r.id,obraId:null,schemaVersion:2,userId:r.userId,requestId:r.id,externalId:text(b.externalId),number:text(b.number),items,total,estimatedTeam,personnelCost,internalCost,grossMargin,pdf,pdfPending:!pdf,validity:'10',payment:text(b.payment,1500),notes:text(b.notes,4000),status:deliveryStatus,deliveryChannel:'',deliveredAt:'',...lifecycle.terms()});put('request',r.userId,{...r,solicitudId:r.solicitudId||r.id,presupuestoIds:[...new Set([...(r.presupuestoIds||[]),q.id])],obraIds:r.obraIds||[],schemaVersion:2,status:recipient?'Presupuestada':'En contacto'});if(recipient)notify(r.userId,'Tu presupuesto está listo','Tenés 10 días corridos desde este envío para aceptar, pedir cambios o rechazar.','/#presupuesto/'+q.id);return q;});return send(res,201,q);
    }
    if(method==='POST'&&/^\/api\/quotes\/[^/]+\/pdf$/.test(p)){requireAdmin(user);const q=get('quote',p.split('/')[3]),pdf=safeFile(user,b.pdfId,'application/pdf'),updated=put('quote',q.userId,{...q,pdf,pdfPending:false,pdfAttachedAt:now()});return send(res,200,updated);}
    if(method==='POST'&&/^\/api\/quotes\/[^/]+\/deliver$/.test(p)){requireAdmin(user);const q=get('quote',p.split('/')[3]);if(!get('request',q.requestId).leadId)fail(409,'Este presupuesto se entrega dentro de la cuenta AMC del cliente.');if(q.status==='Entregado')return send(res,200,q);if(q.status!=='Guardado')fail(409,'Sólo la versión vigente y guardada puede marcarse como entregada.');const channel=['WhatsApp','PDF','Personalmente','Otro'].includes(b.channel)?b.channel:'Otro',updated=put('quote',q.userId,{...q,status:'Entregado',deliveryChannel:channel,deliveredAt:now()});return send(res,200,updated);}
    if(method==='POST'&&/^\/api\/quotes\/[^/]+\/accept-manual$/.test(p)){requireAdmin(user);const q=get('quote',p.split('/')[3]),r=get('request',q.requestId);if(!r.leadId)fail(409,'La aceptación se registra desde la cuenta AMC del cliente.');if(q.status==='Aceptado')return send(res,200,{ok:true,workId:q.obraId});if(q.status!=='Entregado')fail(409,'Primero registrá la entrega de la versión vigente del presupuesto.');const obraId='work-'+q.id;transaction(()=>{put('quote',q.userId,{...q,obraId,status:'Aceptado',acceptedManuallyAt:now(),acceptedBy:user.id});put('request',r.userId,{...r,presupuestoIds:[...new Set([...(r.presupuestoIds||[]),q.id])],obraIds:[...new Set([...(r.obraIds||[]),obraId])],status:'Presupuesto aceptado'});put('work',r.userId,{id:obraId,obraId,presupuestoId:q.id,solicitudId:q.requestId,schemaVersion:2,userId:r.userId,quoteId:q.id,requestId:q.requestId,title:r.service,address:r.address||r.town,status:'Presupuesto aceptado',budget:q.total,payments:[],updates:[],estimatedTeam:q.estimatedTeam||[],personnelCost:q.personnelCost||0,internalCost:q.internalCost||0,grossMargin:q.grossMargin??q.total,start:'',end:''});});return send(res,201,{ok:true,workId:obraId});}
    if(method==='POST'&&/^\/api\/quotes\/[^/]+\/reject-manual$/.test(p)){requireAdmin(user);const q=get('quote',p.split('/')[3]),r=get('request',q.requestId);if(!r.leadId)fail(409,'El rechazo se registra desde la cuenta AMC del cliente.');if(q.status==='Rechazado')return send(res,200,{ok:true});if(q.status!=='Entregado')fail(409,'Primero registrá la entrega del presupuesto.');transaction(()=>{put('quote',q.userId,{...q,status:'Rechazado',rejectedManuallyAt:now(),rejectedBy:user.id});put('request',r.userId,{...r,status:'En contacto',statusUpdatedAt:now()});});return send(res,200,{ok:true});}
    if(method==='POST'&&/^\/api\/quotes\/[^/]+\/reply$/.test(p)){
     lifecycle.run();const q=own(user,get('quote',p.split('/')[3]));if(user.role!=='client')fail(403,'La respuesta corresponde al cliente.');if(!['Aceptado','Cambios solicitados','Rechazado'].includes(b.status))fail(400,'Respuesta inválida.');if(q.status===b.status)return send(res,200,{ok:true});if(q.status!=='Enviado')fail(409,q.status==='Vencido'?'Venció el plazo de 10 días. Escribile a AMC para revisar el presupuesto.':'Este presupuesto ya no admite esa respuesta.');if(b.status==='Cambios solicitados'&&!text(b.message))fail(400,'Contanos qué querés cambiar.');transaction(()=>{if(b.status==='Aceptado'){const r=get('request',q.requestId),obraId='work-'+q.id;put('quote',user.id,{...q,presupuestoId:q.presupuestoId||q.id,solicitudId:q.solicitudId||q.requestId,obraId,schemaVersion:2,status:b.status,reply:text(b.message,4000),repliedAt:now()});put('request',user.id,{...r,solicitudId:r.solicitudId||r.id,presupuestoIds:[...new Set([...(r.presupuestoIds||[]),q.id])],obraIds:[...new Set([...(r.obraIds||[]),obraId])],schemaVersion:2,status:'Presupuesto aceptado'});put('work',user.id,{id:obraId,obraId,presupuestoId:q.id,solicitudId:q.requestId,schemaVersion:2,userId:user.id,quoteId:q.id,requestId:q.requestId,title:r.service,address:r.address||r.town,status:'Presupuesto aceptado',budget:q.total,payments:[],updates:[],estimatedTeam:q.estimatedTeam||[],personnelCost:q.personnelCost||0,internalCost:q.internalCost||0,grossMargin:q.grossMargin??q.total,start:'',end:''});}else{put('quote',user.id,{...q,presupuestoId:q.presupuestoId||q.id,solicitudId:q.solicitudId||q.requestId,obraId:q.obraId||null,schemaVersion:2,status:b.status,reply:text(b.message,4000),repliedAt:now()});const r=get('request',q.requestId);put('request',r.userId,{...r,status:'En contacto',statusUpdatedAt:now()});}const accepted=b.status==='Aceptado',title=accepted?'Presupuesto aceptado':b.status,noticeUrl=accepted?'/#obra-admin/work-'+q.id:'/#presupuesto-admin/'+q.id;notifyAdmins(title,user.name+' · '+q.number,noticeUrl,'important');});return send(res,200,{ok:true});
    }
    if(method==='POST'&&/^\/api\/works\/[^/]+$/.test(p)){requireAdmin(user);get('work',p.split('/')[3]);fail(409,'Las fechas y estados de una obra se actualizan desde Programar, el trabajo del equipo y Cierre de obra.');}
    if(method==='POST'&&/^\/api\/works\/[^/]+\/payments$/.test(p)){requireAdmin(user);const w=get('work',p.split('/')[3]),key=text(b.idempotencyKey);if(!key)fail(400,'Falta la referencia del pago.');if(w.payments.some(x=>x.key===key))return send(res,200,{ok:true});const n=amount(b.amount);if(n>w.budget-w.payments.reduce((a,x)=>a+x.amount,0)+.001||!validDate(b.date)||!text(b.description))fail(400,'Revisá importe, fecha y concepto. El pago no puede superar el saldo.');transaction(()=>{put('work',w.userId,{...w,payments:[...w.payments,{id:id(),key,amount:n,date:b.date,description:text(b.description)}]});notify(w.userId,'Pago registrado','Actualizamos el saldo de tu obra.','/#mi-trabajo/'+w.requestId);});return send(res,200,{ok:true});}
    if(method==='POST'&&/^\/api\/works\/[^/]+\/updates$/.test(p)){requireAdmin(user);const w=get('work',p.split('/')[3]);if(['Pendiente de conformidad','Finalizado'].includes(w.status))fail(409,'La obra ya está cerrada para avances. Usá el cierre de obra para la información final.');const image=safeFile(user,b.photoId,'image/');if(!text(b.text))fail(400,'Describí el avance.');transaction(()=>{put('work',w.userId,{...w,updates:[{id:id(),image,text:text(b.text,4000),date:now()},...w.updates]});notify(w.userId,'Nuevo avance de tu obra','Hay una nueva foto para vos.','/#mi-trabajo/'+w.requestId);});return send(res,201,{ok:true});}
    if(method==='POST'&&p==='/api/posts'){requireAdmin(user);if(!text(b.title)||!text(b.description)||!text(b.town)||!services.includes(b.service))fail(400,'Completá la publicación.');const image=safeFile(user,b.photoId,'image/'),before=b.beforeId?safeFile(user,b.beforeId,'image/'):null;const post=put('post','',{id:id(),title:text(b.title),description:text(b.description,4000),town:text(b.town),service:b.service,date:now(),image,before,demo:false});return send(res,201,post);}
    if(method==='DELETE'&&/^\/api\/posts\/[^/]+$/.test(p)){requireAdmin(user);db.prepare("DELETE FROM docs WHERE id=? AND kind='post'").run(p.split('/')[3]);return send(res,200,{ok:true});}
    if(method==='POST'&&p==='/api/reviews'){if(user.role!=='client')fail(403,'Ingresá con una cuenta de cliente para escribir una reseña.');if(!all('work',user.id).some(w=>w.status==='Finalizado'))fail(409,'Podés dejar una reseña después de confirmar el cierre de una obra.');if(![1,2,3,4,5].includes(Number(b.rating))||text(b.text).length<10)fail(400,'Completá la calificación y al menos 10 caracteres.');const previous=all('review',user.id)[0],review=put('review',user.id,{id:previous?.id||'review-'+user.id,userId:user.id,name:user.name,rating:Number(b.rating),text:text(b.text,1500),date:now(),approved:false});notifyAdmins(previous?'Reseña actualizada':'Nueva reseña','Hay una reseña pendiente de revisión.','/#resenas');return send(res,previous?200:201,review);}
    if(method==='POST'&&/^\/api\/reviews\/[^/]+\/approve$/.test(p)){requireAdmin(user);const r=get('review',p.split('/')[3]);put('review',r.userId,{...r,approved:true});return send(res,200,{ok:true});}
    if(method==='POST'&&p==='/api/referrals'){if(!text(b.name))fail(400,'Ingresá un nombre.');put('referral',user.id,{id:id(),name:text(b.name),note:text(b.note,1000),date:now()});return send(res,201,{ok:true});}
    if(notificationRoutes({p,method,b,user,res}))return;
    if(method==='POST'&&p==='/api/devices'){if(!['web','android'].includes(b.kind)||!validSubscription(b.kind,b.subscription))fail(400,'Suscripción inválida.');const body=JSON.stringify(b.subscription),key=sha(b.kind+':'+(b.kind==='web'?b.subscription.endpoint:b.subscription.token));if(db.prepare('SELECT count(*) AS n FROM devices WHERE userId=?').get(user.id).n>=20&&!db.prepare('SELECT id FROM devices WHERE id=?').get(key))fail(400,'Límite de dispositivos alcanzado.');transaction(()=>{db.prepare('DELETE FROM delivery WHERE deviceId=?').run(key);db.prepare('INSERT INTO devices VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET userId=excluded.userId,body=excluded.body').run(key,user.id,b.kind,body);});return send(res,200,{deviceId:key});}
    fail(404,'Acción no encontrada.');
   }
   if(method!=='GET'&&method!=='HEAD')fail(405,'Método no permitido.');
   if(p==='/presupuestos'){if(!user){res.writeHead(302,{Location:'/#ingresar'});return res.end();}requireAdmin(user);let html=readFileSync(path.join(ROOT,'private/presupuestos-original.html'),'utf8');const saved=all('estimator',user.id)[0]||null;const bootstrap=JSON.stringify({saved,csrf:session.csrf}).replaceAll('<','\\u003c');html=html.replace('<head>','<head><script>window.AMCStored='+bootstrap+';</script>');html=html.replace('</body>','<script src="/amc-busy.js"></script><script src="/amc-confirm.js"></script><script src="/pdf-logo.js"></script><script src="/estimator-sync.js"></script><script src="/presupuestos-bridge.js"></script><script src="/estimator-steps.js"></script></body>');res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(html);}
   const file=path.resolve(ROOT,'public','.'+(p==='/'?'/index.html':p));if(!file.startsWith(path.join(ROOT,'public')+path.sep))fail(404,'No encontrado.');try{const bytes=readFileSync(file);res.setHeader('Content-Type',({'html':'text/html; charset=utf-8','js':'text/javascript; charset=utf-8','css':'text/css; charset=utf-8','jpg':'image/jpeg','png':'image/png','svg':'image/svg+xml','webp':'image/webp','webmanifest':'application/manifest+json'})[file.split('.').pop()]||'application/octet-stream');res.end(method==='HEAD'?undefined:bytes);}catch{fail(404,'No encontrado.');}
  }catch(e){if((!e.status||e.status>=500)&&process.env.NODE_ENV!=='test')console.error(JSON.stringify({level:'error',requestId:req.amcRequestId||'',method:req.method,path:p,status:e.status||500,error:e.code||e.name||'Error'}));else if(process.env.NODE_ENV==='test'&&!e.status)console.error(e);if(!res.headersSent)send(res,e.status||500,{error:e.status?e.message:'Ocurrió un error. Intentá nuevamente.',...(e.requiresTwoFactor?{requiresTwoFactor:true}:{})});else res.end();}
 }
 let delivering=false;
 async function flushPush(){if(delivering)return;delivering=true;try{for(const row of db.prepare("SELECT delivery.*,devices.kind,devices.body AS device,devices.userId FROM delivery JOIN devices ON devices.id=delivery.deviceId WHERE status='pending' AND nextAt<=? ORDER BY CASE WHEN json_extract(delivery.body,'$.priority')='urgent' THEN 0 ELSE 1 END, delivery.rowid LIMIT 20").all(Date.now())){try{const u=db.prepare('SELECT sound FROM users WHERE id=?').get(row.userId);await deliver(row.kind,JSON.parse(row.device),JSON.parse(row.body),keys,!!u?.sound);db.prepare("UPDATE delivery SET status='sent',error='' WHERE id=?").run(row.id);}catch(e){const attempts=row.attempts+1;db.prepare('UPDATE delivery SET attempts=?,status=?,nextAt=?,error=? WHERE id=?').run(attempts,e.gone?'expired':attempts>=6?'failed':'pending',Date.now()+Math.min(3600000,30000*2**attempts),text(e.message,300),row.id);if(e.gone)db.prepare('DELETE FROM devices WHERE id=?').run(row.deviceId);}}}finally{delivering=false;}}
 const server=http.createServer((req,res)=>{const requestId=randomBytes(8).toString('hex'),started=Date.now();req.amcRequestId=requestId;res.setHeader('X-Request-ID',requestId);res.once('finish',()=>{if(process.env.NODE_ENV==='test')return;const pathname=String(req.url||'').split('?')[0];if(res.statusCode>=500){recentServerErrors.push(Date.now());recentErrorCount();}if(pathname==='/healthz'&&res.statusCode<400)return;console.log(JSON.stringify({level:'info',requestId,method:req.method,path:pathname,status:res.statusCode,durationMs:Date.now()-started}));});handle(req,res).catch(error=>{console.error(JSON.stringify({level:'error',requestId,method:req.method,path:String(req.url||'').split('?')[0],status:503,error:error?.code||error?.name||'Unhandled'}));if(!res.headersSent)send(res,503,{error:'No pudimos confirmar la operación. Revisá la conexión y el estado antes de repetirla.'});else res.end();});});server.requestTimeout=30000;server.headersTimeout=10000;const timer=setInterval(()=>flushPush().catch(()=>console.error('No se pudo procesar la cola de avisos.')),5000);timer.unref();const quoteTimer=setInterval(()=>{try{lifecycle.run();}catch{console.error('No se pudo revisar el plazo de presupuestos.');}},60000);quoteTimer.unref();const fileGcTimer=setInterval(()=>cleanupOrphanFiles().catch(()=>console.error('No se pudo limpiar archivos huérfanos.')),6*60*60*1000);fileGcTimer.unref();server.on('close',()=>{clearInterval(timer);clearInterval(quoteTimer);clearInterval(fileGcTimer);db.close();});return {server,db,addUser,flushPush,processQuotes:lifecycle.run,cleanupOrphanFiles};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const demo=process.argv.includes('--demo'),port=Number(process.env.PORT||4180),origin=process.env.AMC_ORIGIN||process.env.RENDER_EXTERNAL_URL||`http://localhost:${port}`;
 if(!demo&&(!origin.startsWith('https:'))){console.error('Producción requiere AMC_ORIGIN=https://tu-dominio. Para prueba local usá node server.mjs --demo.');process.exit(1);}
 if(process.env.RENDER&&!process.env.AMC_DATABASE_URL&&!demo){console.error('Render producción requiere AMC_DATABASE_URL: no se permite guardar en disco temporal.');process.exit(1);}
 const app=createApp({demo,origin,dbPath:process.env.AMC_DB_PATH||path.join(ROOT,'data',demo?'demo.sqlite':'amc.sqlite')});app.server.listen(port,demo&&!process.env.RENDER?'127.0.0.1':'0.0.0.0',()=>console.log('AMC conectado: '+origin+(demo?' · entorno de prueba, cuentas de ejemplo':' ')));
}
