export function stateRoutes({db,all,userView,chatSummary,planning,services,serviceCatalog,team,fieldwork,recovery,closure,staffMessages,staffUnread,staffReadByAdmin,staffReadByEmployee,canAccessWork,employeeWork,clientChatIds,publicQuote,publicWork,systemStatus,twoFactor,lifecycle,beginStateSnapshot,endStateSnapshot,send}){
 return function route({p,method,user,session,res}){
  if(p==='/api/state/system'&&method==='GET'){if(!user){send(res,401,{error:'Ingresá a tu cuenta para continuar.'});return true;}if(user.role!=='admin'){send(res,403,{error:'Acceso restringido.'});return true;}send(res,200,{system:systemStatus()});return true;}
  if(p!=='/api/state'||method!=='GET')return false;
  lifecycle.run();
  const snapshotAll=user?.role==='admin';if(snapshotAll)beginStateSnapshot();try{
   const savedProfile=user?all('clientProfile',user.id)[0]:null,common={user:user?{...userView(user),address:savedProfile?.address||''}:null,...(user?chatSummary(user):{}),csrf:session?.csrf,appearance:planning.appearance(),posts:all('post').filter(p=>!p.demo),reviews:all('review').filter(r=>r.approved),myReview:user?.role==='client'?all('review',user.id)[0]||null:null,services,serviceCatalog};if(!user){send(res,200,common);return true;}
   if(user.role==='employee'){send(res,200,{...common,...team.state(user),...fieldwork.state(user),...recovery.state(user),...closure.state(user),...planning.state(user),notices:all('notice',user.id),staffMessages:staffMessages(user),staffUnread:staffUnread(user),staffReadByAdmin:staffReadByAdmin(user.id),chatRequests:[],messages:[],appointments:[],extras:[],receipts:[],favorites:[],requests:[],quotes:[],works:all('work').filter(w=>canAccessWork(user,w)).map(employeeWork),referrals:[],clients:[],pendingReviews:[]});return true;}
   const leads=user.role==='admin'?all('leadClient'):[],registered=user.role==='admin'?db.prepare("SELECT id,name,email,phone,town,1 AS hasAccount FROM users WHERE role='client'").all().map(c=>{const profile=all('clientProfile',c.id)[0],adminNote=all('clientAdminNote').find(n=>n.clientId===c.id);return {...c,address:profile?.address||'',note:adminNote?.note||'',linkedLeadId:leads.find(l=>l.linkedUserId===c.id)?.id||null};}):[],linkedLeadIds=new Set(leads.filter(l=>l.linkedUserId).map(l=>l.id)),owner=user.role==='admin'?undefined:user.id,allowedChat=user.role==='client'?clientChatIds(user):null;send(res,200,{...common,agendaClients:user.role==='admin'?[...registered,...leads.filter(x=>!linkedLeadIds.has(x.id)).map(x=>({...x,hasAccount:0}))]:[],archivedClients:user.role==='admin'?all('clientArchive').filter(c=>c.archived).map(c=>c.userId):[],offlineNotes:[],staffMessages:user.role==='admin'?staffMessages(user):[],...team.state(user),...fieldwork.state(user),...recovery.state(user),...closure.state(user),...planning.state(user),chatRequests:user.role==='client'?all('request',owner).filter(r=>allowedChat.has(r.id)):undefined,messages:all('message',owner).filter(m=>!allowedChat||allowedChat.has(m.requestId)),appointments:all('appointment',owner),extras:all('extra',owner),receipts:all('receipt',owner),favorites:all('favorite',user.id).map(r=>r.postId),requests:all('request',owner),quotes:all('quote',owner).map(q=>user.role==='admin'?q:publicQuote(q)),works:all('work',owner).map(w=>user.role==='admin'?w:publicWork(w)),notices:all('notice',user.id),referrals:[],clients:[],pendingReviews:[],staffReadByEmployee:user.role==='admin'?staffReadByEmployee():undefined,twoFactor:user.role==='admin'?twoFactor.status(user):undefined});return true;
  }finally{if(snapshotAll)endStateSnapshot();}
 };
}
