export function stateRoutes({all,activeUsers,userView,chatSummary,planning,services,serviceCatalog,team,fieldwork,recovery,closure,staffMessages,staffUnread,staffReadByAdmin,staffReadByEmployee,canAccessWork,employeeWork,clientChatIds,publicQuote,publicWork,systemStatus,twoFactor,beginStateSnapshot,endStateSnapshot,send}){
 return function route({p,method,user,session,res}){
  if(p==='/api/state/system'&&method==='GET'){if(!user){send(res,401,{error:'Ingresá a tu cuenta para continuar.'});return true;}if(user.role!=='admin'){send(res,403,{error:'Acceso restringido.'});return true;}send(res,200,{system:systemStatus()});return true;}
  if(p!=='/api/state'||method!=='GET')return false;
  const snapshot=!!user;if(snapshot)beginStateSnapshot();try{
   const savedProfile=user?all('clientProfile',user.id)[0]:null,appearance=planning.appearance(),publicAppearance=user?.role==='admin'?appearance:(()=>{const {history,...rest}=appearance;return rest;})(),common={user:user?{...userView(user),address:savedProfile?.address||''}:null,...(user?chatSummary(user):{}),csrf:session?.csrf,appearance:publicAppearance,posts:all('post').filter(p=>!p.demo),reviews:all('review').filter(r=>r.approved),myReview:user?.role==='client'?all('review',user.id)[0]||null:null,services,serviceCatalog};if(!user){send(res,200,common);return true;}
   if(user.role==='employee'){send(res,200,{...common,...team.state(user),...fieldwork.state(user),...recovery.state(user),...closure.state(user),...planning.state(user),notices:all('notice',user.id),staffMessages:[],staffUnread:staffUnread(user),staffReadByAdmin:'',chatClients:[],chatRequests:[],messages:[],appointments:[],extras:[],receipts:[],favorites:[],requests:[],quotes:[],works:all('work').filter(w=>canAccessWork(user,w)).map(employeeWork),referrals:[],clients:[],pendingReviews:[]});return true;}
   const leads=user.role==='admin'?all('leadClient'):[],registered=user.role==='admin'?activeUsers('client').map(c=>{const profile=all('clientProfile',c.id)[0],adminNote=all('clientAdminNote').find(n=>n.clientId===c.id);return {...c,hasAccount:1,address:profile?.address||'',note:adminNote?.note||'',linkedLeadId:leads.find(l=>l.linkedUserId===c.id)?.id||null};}):[],linkedLeadIds=new Set(leads.filter(l=>l.linkedUserId).map(l=>l.id)),owner=user.role==='admin'?undefined:user.id,allowedChat=user.role==='client'?clientChatIds(user):null,legacyMessages=all('message',owner).filter(m=>!allowedChat||allowedChat.has(m.requestId)),directMessages=all('clientMessage',owner);send(res,200,{...common,agendaClients:user.role==='admin'?[...registered,...leads.filter(x=>!linkedLeadIds.has(x.id)).map(x=>({...x,hasAccount:0}))]:[],chatClients:user.role==='admin'?registered.map(({id,name,email,phone,town})=>({id,name,email,phone,town})):[{id:user.id,name:user.name,email:user.email,phone:user.phone,town:user.town}],archivedClients:[],offlineNotes:[],staffMessages:[],...team.state(user),...fieldwork.state(user),...recovery.state(user),...closure.state(user),...planning.state(user),chatRequests:user.role==='client'?all('request',owner).filter(r=>allowedChat.has(r.id)):undefined,messages:[...legacyMessages,...directMessages],appointments:all('appointment',owner),extras:all('extra',owner),receipts:all('receipt',owner),favorites:all('favorite',user.id).map(r=>r.postId),requests:all('request',owner),quotes:all('quote',owner).map(q=>user.role==='admin'?q:publicQuote(q)),works:all('work',owner).map(w=>user.role==='admin'?w:publicWork(w)),notices:all('notice',user.id),referrals:[],clients:[],pendingReviews:[],staffReadByEmployee:user.role==='admin'?{}:undefined,twoFactor:user.role==='admin'?{}:undefined});return true;
  }finally{if(snapshot)endStateSnapshot();}
 };
}
