export function teamFeatures({db,all,get,put,transaction,requireAdmin,safeFile,notify,notifyAdmins,send,fail,text,amount,validDate,now,id,sha,addUser,passwordHash}){
 const employees=()=>db.prepare("SELECT id,name,email,phone,active,role FROM users WHERE role IN ('employee','admin') ORDER BY name").all();
 const employee=k=>{const u=db.prepare("SELECT * FROM users WHERE id=? AND role IN ('employee','admin')").get(k);if(!u)fail(404,'Empleado no encontrado.');return u;};
 const operation=(user,value,prefix)=>{if(!/^[\w-]{8,100}$/.test(value||''))fail(400,'Referencia de operación inválida.');return prefix+sha(user.id+':'+value);};
 const previous=(kind,k)=>all(kind).find(x=>x.id===k);
 const tasks=user=>all('assignment',user.role==='admin'?undefined:user.id);
 const purchaseView=user=>user.role==='admin'?all('purchase'):user.role==='client'?all('purchase',user.id).filter(x=>x.sentAt):[];
 const media=(u,p)=>u.role==='employee'?tasks(u).some(t=>t.reports.some(r=>r.photos.includes(p))):purchaseView(u).some(x=>x.file===p);
 function revoke(k){db.prepare('DELETE FROM password_resets WHERE userId=?').run(k);db.prepare('DELETE FROM sessions WHERE userId=?').run(k);db.prepare('DELETE FROM delivery WHERE deviceId IN (SELECT id FROM devices WHERE userId=?)').run(k);db.prepare('DELETE FROM devices WHERE userId=?').run(k);}
 function assignmentData(b){const emp=employee(b.employeeId);if(!emp.active)fail(400,'Ese empleado tiene el acceso desactivado.');const r=get('request',b.requestId);if(!validDate(b.day)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(b.time||'')||!['Trabajo','Visita para presupuesto','Urgencia'].includes(b.type)||!text(b.address,500)||!text(b.instructions,4000))fail(400,'Completá cliente, destino, fecha, hora y tarea.');return {employeeId:emp.id,employeeName:emp.name,requestId:r.id,clientName:r.name,phone:r.phone,service:r.service,address:text(b.address,500),day:b.day,time:b.time,type:b.type,instructions:text(b.instructions,4000),urgent:b.type==='Urgencia'||b.urgent===true};}
 const alert=t=>notify(t.employeeId,t.urgent?'URGENTE · Nuevo destino':'Nuevo destino asignado',t.day+' '+t.time+' · '+t.clientName,'/#tareas',t.urgent?'urgent':'normal');
 async function route({p,method,b,user,res}){let m;
  if(method==='POST'&&(m=p.match(/^\/api\/employees\/([^/]+)\/role$/))){requireAdmin(user);const u=employee(m[1]);if(u.id===user.id)fail(400,'No podés cambiar tu propio rol.');if(!['employee','admin'].includes(b.role))fail(400,'Rol inválido.');transaction(()=>{db.prepare('UPDATE users SET role=? WHERE id=?').run(b.role,u.id);revoke(u.id);put('employeeAudit','',{id:id(),employeeId:u.id,actor:user.id,action:'Rol: '+b.role,date:now()});});send(res,200,{ok:true});return true;}
  if(method==='POST'&&p==='/api/employees'){requireAdmin(user);const u=addUser(text(b.email).toLowerCase(),typeof b.password==='string'?b.password:'',text(b.name),b.role==='admin'?'admin':'employee');send(res,201,{id:u.id,name:u.name,email:u.email,active:true});return true;}
  if(method==='POST'&&(m=p.match(/^\/api\/employees\/([^/]+)\/access$/))){requireAdmin(user);const u=employee(m[1]);if(u.id===user.id)fail(400,'No podés desactivar tu propio acceso.');if(typeof b.active!=='boolean')fail(400,'Estado de acceso inválido.');transaction(()=>{db.prepare('UPDATE users SET active=? WHERE id=?').run(b.active?1:0,u.id);revoke(u.id);put('employeeAudit','',{id:id(),employeeId:u.id,actor:user.id,action:b.active?'Activado':'Desactivado',date:now()});});send(res,200,{ok:true});return true;}
  if(method==='POST'&&(m=p.match(/^\/api\/employees\/([^/]+)\/password$/))){requireAdmin(user);const u=employee(m[1]);if(typeof b.password!=='string'||b.password.length<12||b.password.length>200)fail(400,'Usá una contraseña de 12 a 200 caracteres.');transaction(()=>{db.prepare('UPDATE users SET password=? WHERE id=?').run(passwordHash(b.password),u.id);revoke(u.id);});send(res,200,{ok:true});return true;}
  if(method==='POST'&&p==='/api/assignments'){requireAdmin(user);const k=operation(user,b.idempotencyKey,'assignment-'),old=previous('assignment',k);if(old){send(res,200,old);return true;}const data=assignmentData(b);const t=transaction(()=>{const t=put('assignment',data.employeeId,{id:k,...data,status:'Asignada',reports:[],history:[],date:now(),acknowledgedAt:null});alert(t);return t;});send(res,201,t);return true;}
  if(method==='POST'&&(m=p.match(/^\/api\/assignments\/([^/]+)\/edit$/))){requireAdmin(user);const old=get('assignment',m[1]);if(['Finalizada','Cancelada'].includes(old.status))fail(409,'Esta tarea ya está cerrada. Creá otra asignación.');const data=assignmentData(b);const result=transaction(()=>{const t=put('assignment',data.employeeId,{...old,...data,status:'Asignada',acknowledgedAt:null,reports:old.employeeId===data.employeeId?old.reports:[],history:[...old.history,{...old,history:undefined}],updatedAt:now()});if(old.employeeId!==data.employeeId)notify(old.employeeId,'Destino reasignado','AMC cambió la asignación. Revisá tu agenda.','/#tareas');alert(t);return t;});send(res,200,result);return true;}
  if(method==='POST'&&(m=p.match(/^\/api\/assignments\/([^/]+)\/cancel$/))){requireAdmin(user);const t=get('assignment',m[1]);if(t.status==='Finalizada')fail(409,'La tarea ya finalizó.');if(t.status!=='Cancelada')transaction(()=>{put('assignment',t.employeeId,{...t,status:'Cancelada',updatedAt:now()});notify(t.employeeId,'Asignación cancelada',t.clientName+' · '+t.day,'/#tareas');});send(res,200,{ok:true});return true;}
  if(method==='POST'&&(m=p.match(/^\/api\/assignments\/([^/]+)\/report$/))){const t=get('assignment',m[1]);if(user.role!=='employee'||t.employeeId!==user.id)fail(404,'Asignación no encontrada.');const k=operation(user,b.idempotencyKey,'report-');if(t.reports.some(r=>r.id===k)){send(res,200,{ok:true});return true;}const stages=['Asignada','Recibida','En camino','En el lugar','Finalizada'];if(!stages.includes(b.status)||b.status==='Asignada'||t.status==='Cancelada'||stages.indexOf(b.status)<stages.indexOf(t.status))fail(409,'Estado de tarea inválido.');const files=Array.isArray(b.photos)?b.photos:[];if(files.length>4)fail(400,'Adjuntá hasta cuatro fotos.');if(b.status==='Finalizada'&&!text(b.text,4000))fail(400,'Contá qué se hizo o qué se necesita presupuestar.');const report={id:k,status:b.status,text:text(b.text,4000),photos:files.map(f=>safeFile(user,f,'image/')),date:now()};transaction(()=>{put('assignment',user.id,{...t,status:b.status,acknowledgedAt:t.acknowledgedAt||now(),reports:[...t.reports,report]});notifyAdmins('Novedad del empleado',user.name+' · '+b.status+' · '+t.clientName);});send(res,201,{ok:true});return true;}
  if(method==='POST'&&p==='/api/purchases'){requireAdmin(user);const k=operation(user,b.idempotencyKey,'purchase-'),old=previous('purchase',k);if(old){send(res,200,old);return true;}const r=get('request',b.requestId);if(!validDate(b.day)||b.day>now().slice(0,10)||!text(b.vendor)||!text(b.detail,4000)||!text(b.reference))fail(400,'Completá fecha, comercio, comprobante y detalle de la compra.');const purchase=put('purchase',r.userId,{id:k,userId:r.userId,requestId:r.id,clientName:r.name,service:r.service,day:b.day,vendor:text(b.vendor),reference:text(b.reference),detail:text(b.detail,4000),amount:amount(b.amount),file:safeFile(user,b.fileId),createdBy:user.id,date:now(),sentAt:null});send(res,201,purchase);return true;}
  if(method==='POST'&&(m=p.match(/^\/api\/purchases\/([^/]+)\/send$/))){requireAdmin(user);const purchase=get('purchase',m[1]);if(!purchase.sentAt)transaction(()=>{put('purchase',purchase.userId,{...purchase,sentAt:now()});notify(purchase.userId,'AMC compartió una compra','Podés ver el detalle y la factura o recibo de tu proyecto.','/#compras');});send(res,200,{ok:true});return true;}
  return false;
 }
 // Explicit public employee payload: no history from other assignees, money or customer database.
 const quoteStatus=requestId=>{const qs=all('quote').filter(q=>q.requestId===requestId);const q=qs.find(q=>q.status==='Aceptado')||qs.find(q=>q.status!=='Reemplazado');return q?{status:q.status==='Enviado'?(q.seenAt?'Visto · esperando respuesta':'Enviado · esperando respuesta'):q.status,expiresAt:q.expiresAt||null}:{status:'Pendiente de presupuestar',expiresAt:null};};
 const board=user=>{const seen=new Set();return tasks(user).filter(t=>t.status!=='Cancelada'&&!seen.has(t.requestId)&&seen.add(t.requestId)).map(t=>({assignmentId:t.id,clientName:t.clientName,service:t.service,employeeName:t.employeeName,...quoteStatus(t.requestId)}));};
 const assignmentView=t=>({id:t.id,employeeId:t.employeeId,employeeName:t.employeeName,clientName:t.clientName,phone:t.phone,service:t.service,address:t.address,day:t.day,time:t.time,type:t.type,instructions:t.instructions,urgent:t.urgent,status:t.status,acknowledgedAt:t.acknowledgedAt,reports:t.reports,date:t.date,quoteStatus:quoteStatus(t.requestId)});
 return {route,media,state:user=>({quoteBoard:user.role==='client'?[]:board(user),employees:user.role==='admin'?employees():[],assignments:user.role==='client'?[]:tasks(user).map(t=>user.role==='admin'?{...t,quoteStatus:quoteStatus(t.requestId)}:assignmentView(t)),purchases:purchaseView(user)})};
}

