import test from 'node:test';import assert from 'node:assert/strict';import {createApp} from '../server.mjs';import {rangeSlots} from '../public/calendar-rules.js';
test('private calendar, weekends, conflicts, appearance and account estimator persistence',async()=>{const origin='http://localhost:4180',app=createApp({dbPath:':memory:',demo:true,origin});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;const actor=()=>({cookie:'',csrf:'',async call(p,b,status=200){const r=await fetch(base+p,{method:b===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:this.cookie,'X-CSRF-Token':this.csrf},...(b===undefined?{}:{body:JSON.stringify(b)})});const v=r.headers.get('content-type')?.includes('json')?await r.json():await r.text();assert.equal(r.status,status,JSON.stringify(v));if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(v.csrf)this.csrf=v.csrf;return v;}});try{const a=actor(),c=actor(),g=actor(),e=actor();await a.call('/api/login',{email:'admin@amc.test',password:'AMC-Prueba-2026!'});await c.call('/api/login',{email:'cliente@amc.test',password:'Cliente-Prueba-2026!'});await a.call('/api/employees',{name:'Equipo',email:'employee@test.local',password:'Employee-Test-2026!'},201);await e.call('/api/login',{email:'employee@test.local',password:'Employee-Test-2026!'});
assert.deepEqual(rangeSlots('2026-09-05','2026-09-07'),[{day:'2026-09-05',part:'Mañana'},{day:'2026-09-07',part:'Mañana'},{day:'2026-09-07',part:'Tarde'}]);
const booking={kind:'Reserva',status:'Confirmada',title:'Obra de prueba',start:'2026-09-05',end:'2026-09-07',slot:'Día completo',teamIds:[],idempotencyKey:'reserve-001'};await c.call('/api/calendar-bookings',booking,403);const saved=await a.call('/api/calendar-bookings',booking,201);await a.call('/api/calendar-bookings',{...booking,idempotencyKey:'reserve-002'},409);await a.call('/api/calendar-bookings',{...booking,start:'2026-09-06',end:'2026-09-06',idempotencyKey:'reserve-003'},400);assert.equal((await c.call('/api/state')).calendarEvents,undefined);assert.equal((await e.call('/api/state')).calendarEvents,undefined);await a.call('/api/calendar-bookings/'+saved.id+'/cancel',{});assert.equal((await a.call('/api/state')).calendarEvents.length,0);
assert.equal((await g.call('/api/state')).posts.length,0);const photo=await a.call('/api/upload',{mime:'image/jpeg',base64:Buffer.from([255,216,255,224,0,0]).toString('base64')},201);await a.call('/api/appearance',{title:'AMC',subtitle:'Trabajos reales',photos:[{id:photo.id,caption:'Mi trabajo'}]});await g.call(photo.url);await c.call('/api/appearance',{title:'Otra',subtitle:'Cambio',photos:[]},403);await a.call('/api/appearance',{title:'AMC',subtitle:'Trabajos reales',photos:[]});await g.call(photo.url,undefined,404);
const payload={revision:0,db:{settings:{},quotes:[],customTariffs:[],overrides:{}},draft:{items:[],client:'Guardado </script><script>alert(1)</script>'}};await c.call('/api/estimator-state',payload,403);await e.call('/api/estimator-state',payload,403);await a.call('/api/estimator-state',payload);await a.call('/api/estimator-state',payload,409);const a2=actor();await a2.call('/api/login',{email:'admin@amc.test',password:'AMC-Prueba-2026!'});const html=await a2.call('/presupuestos');assert.ok(html.includes('window.AMCStored='));assert.ok(html.includes('Guardado \\u003c/script>'));assert.ok(!html.includes('Guardado </script>'));assert.equal(JSON.parse(app.db.prepare("SELECT body FROM docs WHERE kind='estimator'").get().body).draft.client,payload.draft.client);
}finally{await new Promise(r=>app.server.close(r));}});

test('programming a work keeps calendar dates and work status in sync',async()=>{
 const origin='http://localhost:4180',app=createApp({dbPath:':memory:',origin}),admin=app.addUser('calendar-admin@amc.test','Calendar-Admin-2026!','AMC','admin'),client=app.addUser('calendar-client@amc.test','Calendar-Client-2026!','Cliente','client');
 const insert=(id,kind,owner,body)=>app.db.prepare('INSERT INTO docs(id,kind,owner,body) VALUES(?,?,?,?)').run(id,kind,owner,JSON.stringify(body));
 const request={id:'request-calendar-work',userId:client.id,name:'Cliente',service:'Pintura',status:'Presupuesto aceptado'},quote={id:'quote-calendar-work',userId:client.id,requestId:request.id,status:'Aceptado'},work={id:'work-calendar-work',userId:client.id,quoteId:quote.id,requestId:request.id,title:'Pintura',status:'Presupuesto aceptado',start:'',end:'',payments:[],updates:[]};
 insert(request.id,'request',client.id,request);insert(quote.id,'quote',client.id,quote);insert(work.id,'work',client.id,work);
 await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port,actor=()=>({cookie:'',csrf:'',async call(p,b,status=200){const r=await fetch(base+p,{method:b===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:this.cookie,'X-CSRF-Token':this.csrf},...(b===undefined?{}:{body:JSON.stringify(b)})});const v=await r.json();assert.equal(r.status,status,JSON.stringify(v));if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(v.csrf)this.csrf=v.csrf;return v;}});
 try{
  const a=actor(),c=actor();await a.call('/api/login',{email:admin.email,password:'Calendar-Admin-2026!'});await c.call('/api/login',{email:client.email,password:'Calendar-Client-2026!'});
  const payload={kind:'Obra',status:'Confirmada',title:'Pintura',workId:work.id,start:'2030-02-04',end:'2030-02-05',slot:'Día completo',teamIds:[],idempotencyKey:'work-calendar-confirmed'};
  const saved=await a.call('/api/calendar-bookings',payload,201);let stored=JSON.parse(app.db.prepare('SELECT body FROM docs WHERE id=?').get(work.id).body);assert.equal(stored.status,'Trabajo programado');assert.equal(stored.start,'2030-02-04');assert.equal(stored.calendarBookingId,saved.id);
  await a.call('/api/calendar-bookings/'+saved.id+'/cancel',{});stored=JSON.parse(app.db.prepare('SELECT body FROM docs WHERE id=?').get(work.id).body);assert.equal(stored.status,'Presupuesto aceptado');assert.equal(stored.start,'');assert.equal(stored.calendarBookingId,null);
  const proposal=await a.call('/api/calendar-bookings',{...payload,status:'Propuesta',start:'2030-02-07',end:'2030-02-08',idempotencyKey:'work-calendar-proposal'},201);stored=JSON.parse(app.db.prepare('SELECT body FROM docs WHERE id=?').get(work.id).body);assert.equal(stored.status,'Presupuesto aceptado');assert.equal(stored.start,'');
  await c.call('/api/date-proposals/'+proposal.id+'/reply',{status:'Confirmada',revision:proposal.updatedAt});stored=JSON.parse(app.db.prepare('SELECT body FROM docs WHERE id=?').get(work.id).body);assert.equal(stored.status,'Trabajo programado');assert.equal(stored.start,'2030-02-07');assert.equal(stored.calendarBookingId,proposal.id);
  const employee=await a.call('/api/employees',{name:'Operario calendario',email:'calendar-worker@amc.test',password:'Calendar-Worker-2026!',phone:'1',specialty:'Pintura',dailyCost:50000,hourlyCost:0},201);await a.call('/api/works/'+work.id+'/assign-team',{day:'2030-02-07',time:'09:00',address:'La Falda',instructions:'Realizar pintura',members:[{employeeId:employee.id,dailyCost:55000,estimatedDays:2}],idempotencyKey:'calendar-work-team'},201);stored=JSON.parse(app.db.prepare('SELECT body FROM docs WHERE id=?').get(work.id).body);assert.equal(stored.start,'2030-02-07');assert.equal(stored.end,'2030-02-08');assert.equal(stored.status,'Trabajo programado');let syncedBooking=JSON.parse(app.db.prepare('SELECT body FROM docs WHERE id=?').get(proposal.id).body);assert.deepEqual(syncedBooking.teamIds,[employee.id]);
  await a.call('/api/calendar-bookings/'+proposal.id+'/edit',{...payload,status:'Confirmada',start:'2030-02-11',end:'2030-02-12',teamIds:[employee.id],idempotencyKey:'ignored-on-edit'});stored=JSON.parse(app.db.prepare('SELECT body FROM docs WHERE id=?').get(work.id).body);assert.equal(stored.start,'2030-02-11');let task=JSON.parse(app.db.prepare("SELECT body FROM docs WHERE kind='assignment' AND owner=?").get(employee.id).body);assert.equal(task.day,'2030-02-11');assert.equal(task.schedulePending,false);assert.equal((await a.call('/api/state')).calendarBookings.filter(x=>x.workId===work.id&&x.status!=='Cancelada').length,1);
  await a.call('/api/calendar-bookings/'+proposal.id+'/cancel',{});task=JSON.parse(app.db.prepare("SELECT body FROM docs WHERE kind='assignment' AND owner=?").get(employee.id).body);assert.equal(task.schedulePending,true);
  const fresh=await a.call('/api/calendar-bookings',{...payload,status:'Confirmada',start:'2030-02-14',end:'2030-02-15',teamIds:[employee.id],idempotencyKey:'work-calendar-fresh'},201);task=JSON.parse(app.db.prepare("SELECT body FROM docs WHERE kind='assignment' AND owner=?").get(employee.id).body);assert.equal(task.day,'2030-02-14');assert.equal(task.schedulePending,false);stored=JSON.parse(app.db.prepare('SELECT body FROM docs WHERE id=?').get(work.id).body);assert.equal(stored.calendarBookingId,fresh.id);
 }finally{await new Promise(r=>app.server.close(r));}
});


test('agenda and team use the same availability rules',async()=>{
 const origin='http://localhost:4180',app=createApp({dbPath:':memory:',origin}),admin=app.addUser('schedule-admin@amc.test','Schedule-Admin-2026!','AMC','admin'),client=app.addUser('schedule-client@amc.test','Schedule-Client-2026!','Cliente','client');
 const addRequest=(id,name)=>app.db.prepare('INSERT INTO docs(id,kind,owner,body) VALUES(?,?,?,?)').run(id,'request',client.id,JSON.stringify({id,userId:client.id,name,phone:'3548000000',town:'La Falda',service:'Pintura',description:'Visita',status:'Nueva',date:new Date().toISOString()}));
 addRequest('schedule-request-a','Cliente A');addRequest('schedule-request-b','Cliente B');
 await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port,actor=()=>({cookie:'',csrf:'',async call(p,b,status=200){const r=await fetch(base+p,{method:b===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:this.cookie,'X-CSRF-Token':this.csrf},...(b===undefined?{}:{body:JSON.stringify(b)})});const v=await r.json();assert.equal(r.status,status,JSON.stringify(v));if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(v.csrf)this.csrf=v.csrf;return v;}});
 try{
  const a=actor();await a.call('/api/login',{email:admin.email,password:'Schedule-Admin-2026!'});const employee=await a.call('/api/employees',{name:'Operario agenda',email:'schedule-worker@amc.test',password:'Schedule-Worker-2026!',dailyCost:50000},201);
  const reserve=await a.call('/api/calendar-bookings',{kind:'Reserva',status:'Confirmada',title:'Otro compromiso',start:'2030-04-10',end:'2030-04-10',slot:'Mañana',teamIds:[employee.id],idempotencyKey:'schedule-reserve'},201);
  await a.call('/api/requests/schedule-request-a/appointment',{day:'2030-04-10',time:'10:00',duration:60,address:'La Falda'},409);
  await a.call('/api/assignments',{employeeId:employee.id,requestId:'schedule-request-b',type:'Visita para presupuesto',day:'2030-04-10',time:'10:00',address:'La Falda',instructions:'Medir',idempotencyKey:'schedule-assignment-conflict'},409);
  await a.call('/api/calendar-bookings/'+reserve.id+'/cancel',{});
  await a.call('/api/requests/schedule-request-a/appointment',{day:'2030-04-10',time:'10:00',duration:60,address:'La Falda'});
  await a.call('/api/assignments',{employeeId:employee.id,requestId:'schedule-request-a',type:'Visita para presupuesto',day:'2030-04-10',time:'10:00',address:'La Falda',instructions:'Medir',idempotencyKey:'schedule-assignment-ok'},201);
  const events=(await a.call('/api/state')).calendarEvents.filter(e=>e.requestId==='schedule-request-a'&&e.start==='2030-04-10');assert.equal(events.length,1);assert.equal(events[0].source,'appointment');assert.deepEqual(events[0].teamIds,[employee.id]);
  await a.call('/api/assignments',{employeeId:employee.id,requestId:'schedule-request-b',type:'Visita para presupuesto',day:'2030-04-10',time:'10:00',address:'La Falda',instructions:'Otra visita',idempotencyKey:'schedule-double-book'},409);
 }finally{await new Promise(r=>app.server.close(r));}
});
