import test from 'node:test';import assert from 'node:assert/strict';import {createApp} from '../server.mjs';
async function fixture(options={}){const origin='http://localhost:4180',app=createApp({dbPath:':memory:',origin,...options});app.addUser('owner@amc.test','Strong-Owner-2026!','AMC','admin');await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;const actor=()=>({cookie:'',csrf:'',async call(p,b,status=200){const r=await fetch(base+p,{method:b===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:this.cookie,'X-CSRF-Token':this.csrf},...(b===undefined?{}:{body:JSON.stringify(b)})});const data=(r.headers.get('content-type')||'').includes('json')?await r.json():await r.text();assert.equal(r.status,status,JSON.stringify(data));if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(data.csrf)this.csrf=data.csrf;return data;}});return {app,actor,close:()=>new Promise(r=>app.server.close(r))};}
test('date proposals protect privacy and revisions, accept and request alternatives; private thumbnails',async()=>{const {actor,close}=await fixture();try{const a=actor(),c=actor(),o=actor();await a.call('/api/login',{email:'owner@amc.test',password:'Strong-Owner-2026!'});await c.call('/api/register',{email:'client@amc.test',name:'Cliente',password:'12345678'});await o.call('/api/register',{email:'other@amc.test',name:'Otro',password:'12345678'});
const photo=await c.call('/api/upload',{mime:'image/jpeg',base64:Buffer.from([255,216,255,1,2,3]).toString('base64'),thumbnail:Buffer.from([255,216,255,4]).toString('base64')},201);
await o.call(photo.url+'?thumb=1',undefined,404);const r=await c.call('/api/requests',{name:'Cliente',phone:'1234',town:'La Falda',description:'Pintar',service:'Pintura',type:'presupuesto',photos:[photo.id]},201);await a.call(photo.url+'?thumb=1');
const payload={kind:'Reserva',status:'Propuesta',title:'Comienzo',requestId:r.id,start:'2030-01-07',end:'2030-01-08',slot:'Día completo',teamIds:[],notes:'PRIVATE',idempotencyKey:'proposal-0001'};
const b=await a.call('/api/calendar-bookings',payload,201);const cs=await c.call('/api/state');assert.equal(cs.dateProposals[0].status,'Propuesta');assert.equal(JSON.stringify(cs.dateProposals).includes('PRIVATE'),false);assert.equal((await o.call('/api/state')).dateProposals.length,0);
await o.call('/api/date-proposals/'+b.id+'/reply',{status:'Confirmada',revision:b.updatedAt},404);await c.call('/api/date-proposals/'+b.id+'/reply',{status:'Confirmada',revision:'old'},409);await c.call('/api/date-proposals/'+b.id+'/reply',{status:'Cambio solicitado',revision:b.updatedAt},400);await c.call('/api/date-proposals/'+b.id+'/reply',{status:'Confirmada',revision:b.updatedAt});assert.equal((await c.call('/api/state')).requests[0].scheduledStart,b.start);await c.call('/api/date-proposals/'+b.id+'/reply',{status:'Cambio solicitado',revision:b.updatedAt,message:'Otro día'},409);
const second=await a.call('/api/calendar-bookings',{...payload,start:'2030-01-10',end:'2030-01-11',idempotencyKey:'proposal-0002'},201);await c.call('/api/date-proposals/'+second.id+'/reply',{status:'Cambio solicitado',revision:second.updatedAt,message:'Prefiero el lunes'});assert.equal((await a.call('/api/state')).dateProposals.find(x=>x.id===second.id).status,'Cambio solicitado');
}finally{await close();}});
