import test from 'node:test';import assert from 'node:assert/strict';import {createApp} from '../server.mjs';import {quoteLifecycle} from '../quote-lifecycle.mjs';
const DAY=86400000;
test('ten-day deadline, reminder deduplication, employee status without prices, rejection and late response protection',async()=>{
 let clock=Date.now();const origin='http://localhost:4180',app=createApp({dbPath:':memory:',origin,clock:()=>clock});app.addUser('owner@amc.test','Strong-Owner-2026!','AMC','admin');await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
 const actor=()=>({cookie:'',csrf:'',async call(p,b,status=200){const r=await fetch(base+p,{method:b===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:this.cookie,'X-CSRF-Token':this.csrf},...(b===undefined?{}:{body:JSON.stringify(b)})});const data=await r.json();assert.equal(r.status,status,JSON.stringify(data));if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(data.csrf)this.csrf=data.csrf;return data;}});
 try{const admin=actor(),client=actor(),employee=actor();await admin.call('/api/login',{email:'owner@amc.test',password:'Strong-Owner-2026!'});await client.call('/api/register',{email:'client@amc.test',password:'Strong-Client-2026!',name:'Cliente'});const account={email:'employee@amc.test',password:'Strong-Employee-2026!',name:'Empleado'};const emp=await admin.call('/api/employees',account,201);await employee.call('/api/login',account);
 const request=()=>client.call('/api/requests',{name:'Cliente',phone:'3515550100',town:'La Falda',description:'Pintura del living',service:'Pintura',type:'presupuesto'},201);const req=await request();await admin.call('/api/assignments',{employeeId:emp.id,requestId:req.id,type:'Visita para presupuesto',day:'2030-01-01',time:'10:00',address:'La Falda',instructions:'Tomar medidas',idempotencyKey:'assignment-clock-001'},201);assert.equal((await employee.call('/api/state')).quoteBoard[0].status,'Pendiente de presupuestar');
 const pdf=await admin.call('/api/upload',{mime:'application/pdf',base64:Buffer.from('%PDF-1.4\nexample').toString('base64')},201);const send=(r,version='a',externalId='quote-clock')=>admin.call('/api/quotes',{requestId:r.id,externalId,version:version.repeat(64),number:'AMC-TEST',items:[{description:'Pintura'}],total:1000,pdfId:pdf.id,validity:'999'},201);const q=await send(req),sent=clock;assert.equal(q.validity,'10');assert.equal(Date.parse(q.expiresAt)-Date.parse(q.date),10*DAY);let board=(await employee.call('/api/state')).quoteBoard[0];assert.equal(board.status,'Enviado · esperando respuesta');assert.deepEqual(Object.keys(board).sort(),['assignmentId','clientName','employeeName','expiresAt','service','status'].sort());assert.equal((await employee.call('/api/state')).quotes.length,0);await client.call('/api/quotes/'+q.id+'/view',{});assert.equal((await employee.call('/api/state')).quoteBoard[0].status,'Visto · esperando respuesta');
 const count=()=>app.db.prepare("SELECT count(*) n FROM docs WHERE kind='notice' AND owner=?").get(q.userId).n;const initial=count();clock=sent+3*DAY-1;app.processQuotes();assert.equal(count(),initial);for(const [day,n] of [[3,1],[7,2],[9,3]]){clock=sent+day*DAY;app.processQuotes();app.processQuotes();assert.equal(count(),initial+n);}clock=sent+10*DAY;await client.call('/api/quotes/'+q.id+'/reply',{status:'Aceptado'},409);assert.equal((await client.call('/api/state')).works.length,0);assert.equal((await employee.call('/api/state')).quoteBoard[0].status,'Vencido');const expiredCount=count();app.processQuotes();assert.equal(count(),expiredCount);
 const req2=await request(),q2=await send(req2,'b');await client.call('/api/quotes/'+q2.id+'/reply',{status:'Rechazado'});await client.call('/api/quotes/'+q2.id+'/reply',{status:'Rechazado'});const stopped=count();clock+=11*DAY;app.processQuotes();assert.equal(count(),stopped);assert.equal((await client.call('/api/state')).quotes.find(x=>x.id===q2.id).status,'Rechazado');
 const req3=await request(),q3=await send(req3,'c');clock=Date.parse(q3.expiresAt)-1;await client.call('/api/quotes/'+q3.id+'/reply',{status:'Aceptado'});assert.equal((await client.call('/api/state')).works.length,1);clock+=DAY;app.processQuotes();assert.equal((await client.call('/api/state')).quotes.find(x=>x.id===q3.id).status,'Aceptado');
 }finally{await new Promise(r=>app.server.close(r));}
});
test('restart keeps reminder markers and downtime sends only the latest relevant reminder',()=>{
 let clock=0,notifications=0;const quotes=new Map([['q',{id:'q',userId:'client',number:'AMC',date:new Date(0).toISOString(),status:'Enviado'}]]);const dependencies={all:()=>[...quotes.values()],put:(_kind,_user,q)=>quotes.set(q.id,q),transaction:fn=>fn(),notify:()=>notifications++,notifyAdmins:()=>{},clock:()=>clock};let lifecycle=quoteLifecycle(dependencies);clock=8*DAY;lifecycle.run();assert.equal(notifications,1);assert.equal(quotes.get('q').reminderStage,7);lifecycle=quoteLifecycle(dependencies);lifecycle.run();assert.equal(notifications,1);clock=9*DAY;lifecycle.run();assert.equal(notifications,2);quotes.set('q',{...quotes.get('q'),status:'Reemplazado'});clock=11*DAY;lifecycle.run();assert.equal(quotes.get('q').status,'Reemplazado');assert.equal(notifications,2);
});
