import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';
import {createApp} from '../server.mjs';import {exportBackup,verifyBackup,restoreBackup} from '../secure-backup.mjs';
test('encrypted backup restores accounts, documents and photo bytes; rejects corruption, wrong keys and nonempty destinations',()=>{
 const dir=mkdtempSync(path.join(tmpdir(),'amc-backup-')),file=path.join(dir,'copy.amcbak'),password='Backup-Test-Only-2026!';const source=createApp({dbPath:':memory:'}),target=createApp({dbPath:':memory:'});
 try{const u=source.addUser('restore@test.test','12345678','Cliente de respaldo');source.db.prepare('INSERT INTO docs(id,kind,owner,body) VALUES(?,?,?,?)').run('r1','request',u.id,JSON.stringify({id:'r1',userId:u.id,description:'Trabajo privado'}));const bytes=Buffer.from([255,216,255,1,2,3]);source.db.prepare('INSERT INTO files VALUES(?,?,?,?)').run('photo1',u.id,'image/jpeg',bytes);source.db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run('old-session',u.id,Date.now()+999999,'old-csrf');
  const result=exportBackup(source.db,file,password);assert.ok(result.records>=4);assert.equal(readFileSync(file).includes(Buffer.from('Trabajo privado')),false);assert.deepEqual(verifyBackup(file,password),result);assert.throws(()=>verifyBackup(file,'Different-password!'));assert.equal(target.db.prepare('SELECT count(*) AS n FROM users').get().n,0);
  const broken=path.join(dir,'broken.amcbak'),buffer=readFileSync(file);buffer[60]^=1;writeFileSync(broken,buffer);assert.throws(()=>restoreBackup(target.db,broken,password));writeFileSync(broken,readFileSync(file).subarray(0,-8));assert.throws(()=>verifyBackup(broken,password));
  assert.deepEqual(restoreBackup(target.db,file,password),result);assert.equal(target.db.prepare('SELECT name FROM users').get().name,'Cliente de respaldo');assert.equal(JSON.parse(target.db.prepare('SELECT body FROM docs WHERE id=?').get('r1').body).description,'Trabajo privado');assert.deepEqual(Buffer.from(target.db.prepare('SELECT body FROM files WHERE id=?').get('photo1').body),bytes);assert.equal(target.db.prepare('SELECT count(*) AS n FROM sessions').get().n,0);assert.throws(()=>restoreBackup(target.db,file,password),/base vacía/);assert.equal(target.db.prepare('SELECT count(*) AS n FROM users').get().n,1);
 }finally{source.server.close();target.server.close();rmSync(dir,{recursive:true,force:true});}
});
