import test from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from '../server.mjs';
import {readFileSync} from 'node:fs';

const origin='http://localhost:4180';
const actor=base=>({cookie:'',csrf:'',async call(path,body,status=200){const response=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:this.cookie,'X-CSRF-Token':this.csrf},...(body===undefined?{}:{body:JSON.stringify(body)})});const result=response.headers.get('content-type')?.includes('json')?await response.json():await response.text();assert.equal(response.status,status,JSON.stringify(result));if(response.headers.get('set-cookie'))this.cookie=response.headers.get('set-cookie').split(';')[0];if(result.csrf)this.csrf=result.csrf;return result;}});

test('stage 6 full client-admin-multiemployee lifecycle, rejection and no-take',async()=>{
 const app=createApp({dbPath:':memory:',origin});app.addUser('owner@amc.test','Owner-Stage6!','AMC','admin');await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+app.server.address().port;
 try{
  const admin=actor(base),client=actor(base),workerA=actor(base),workerB=actor(base);await admin.call('/api/login',{email:'owner@amc.test',password:'Owner-Stage6!'});await client.call('/api/register',{email:'stage6@amc.test',password:'Cliente-Stage6!',name:'Cliente Punilla'});
  const request=await client.call('/api/requests',{name:'Cliente Punilla',phone:'3548000000',town:'La Falda',type:'presupuesto',services:['Revoque fino','Porcelanato','Interior'],description:'Revoque, porcelanato y pintura interior',photos:[]},201);assert.deepEqual(request.rubrics,['Albañilería','Pintura']);assert.equal(request.services.length,3);
  const adminState=await admin.call('/api/state');assert.ok(adminState.notices.some(n=>n.url==='/#solicitud/'+request.id));assert.deepEqual(adminState.requests[0].rubrics,['Albañilería','Pintura']);
  const empA=await admin.call('/api/employees',{name:'Carlos',email:'carlos@amc.test',password:'Empleado-Carlos!',phone:'1',specialty:'Albañilería',dailyCost:30000,hourlyCost:5000},201);const empB=await admin.call('/api/employees',{name:'Pedro',email:'pedro@amc.test',password:'Empleado-Pedro!',phone:'2',specialty:'Pintura',dailyCost:60000,hourlyCost:8000},201);
  const pdf=await admin.call('/api/upload',{mime:'application/pdf',base64:Buffer.from('%PDF-1.4\nstage6').toString('base64')},201);const quote=await admin.call('/api/quotes',{requestId:request.id,externalId:'stage6-main',version:'6'.repeat(64),number:'AMC-S6',items:[{description:'Trabajos solicitados'}],total:1000000,internalCost:370000,estimatedTeam:[{employeeId:empA.id,name:'Carlos',dailyCost:30000,days:3},{employeeId:empB.id,name:'Pedro',dailyCost:60000,days:3}],pdfId:pdf.id},201);assert.equal(quote.status,'Enviado');assert.equal(quote.personnelCost,270000);assert.equal(quote.internalCost,370000);assert.equal(quote.grossMargin,630000);assert.equal(quote.grossMargin/quote.total*100,63);
  const clientState=await client.call('/api/state');assert.equal(clientState.quotes[0].id,quote.id);assert.equal(clientState.quotes[0].internalCost,undefined);assert.equal(clientState.quotes[0].estimatedTeam,undefined);assert.ok(clientState.notices.some(n=>n.url==='/#presupuesto/'+quote.id));
  await client.call('/api/quotes/'+quote.id+'/reply',{status:'Aceptado'});const work=(await admin.call('/api/state')).works.find(w=>w.requestId===request.id);assert.equal(work.estimatedTeam.length,2);await admin.call('/api/calendar-bookings',{kind:'Obra',status:'Confirmada',title:'Trabajos solicitados',workId:work.id,start:'2030-03-11',end:'2030-03-14',slot:'Día completo',teamIds:[],idempotencyKey:'stage6-work-date'},201);
  const assignment={day:'2030-03-11',time:'09:00',address:'La Falda',instructions:'Comenzar obra'};const assigned=await admin.call('/api/works/'+work.id+'/assign-team',{...assignment,members:[{employeeId:empA.id,dailyCost:35000,estimatedDays:4},{employeeId:empB.id,dailyCost:60000,estimatedDays:4}],idempotencyKey:'stage6-team'},201);assert.equal(assigned.assignments.length,2);await admin.call('/api/works/'+work.id+'/assign-team',{...assignment,time:'08:30',members:[{employeeId:empA.id,dailyCost:40000,estimatedDays:5},{employeeId:empB.id,dailyCost:60000,estimatedDays:4}],idempotencyKey:'stage6-team-too-early'},400);const editedTeam=await admin.call('/api/works/'+work.id+'/assign-team',{...assignment,time:'09:30',members:[{employeeId:empA.id,dailyCost:40000,estimatedDays:5},{employeeId:empB.id,dailyCost:60000,estimatedDays:4}],idempotencyKey:'stage6-team-edit'});assert.equal(editedTeam.assignments.length,2);assert.equal(editedTeam.assignments.find(x=>x.employeeId===empA.id).dailyCost,40000);const activeAssignments=(await admin.call('/api/state')).assignments.filter(x=>x.requestId===request.id&&x.status!=='Cancelada');assert.equal(activeAssignments.length,2);const actual=await admin.call('/api/works/'+work.id+'/labor',{members:[{assignmentId:activeAssignments.find(x=>x.employeeId===empA.id).id,actualDays:4,paid:true,paidAmount:160000,paymentDate:'2030-03-15',paymentNote:'Transferencia'},{assignmentId:activeAssignments.find(x=>x.employeeId===empB.id).id,actualDays:3,paid:false}],otherActual:100000});assert.equal(actual.actualPersonnelCost,340000);assert.equal(actual.finalCost,440000);assert.equal(actual.realProfit,560000);const privateWork=(await client.call('/api/state')).works[0];assert.equal(privateWork.actualPersonnelCost,undefined);assert.equal(privateWork.realProfit,undefined);
  await workerA.call('/api/login',{email:'carlos@amc.test',password:'Empleado-Carlos!'});await workerB.call('/api/login',{email:'pedro@amc.test',password:'Empleado-Pedro!'});let aState=await workerA.call('/api/state'),bState=await workerB.call('/api/state');assert.equal(aState.assignments.length,1);assert.equal(bState.assignments.length,1);assert.equal(aState.assignments[0].dailyCost,undefined);
  await workerA.call('/api/assignments/'+aState.assignments[0].id+'/report',{status:'En el lugar',category:'Durante',text:'Comenzamos',photos:[],idempotencyKey:'stage6-start'},201);assert.equal((await client.call('/api/state')).works[0].status,'En ejecución');
  await workerA.call('/api/assignments/'+aState.assignments[0].id+'/report',{status:'Finalizada',category:'Después',text:'Parte de Carlos terminada',photos:[],idempotencyKey:'stage6-finish-a'},201);assert.equal((await client.call('/api/state')).works[0].status,'En ejecución');await workerB.call('/api/assignments/'+bState.assignments[0].id+'/report',{status:'Finalizada',category:'Después',text:'Parte de Pedro terminada',photos:[],idempotencyKey:'stage6-finish-b'},201);assert.equal((await client.call('/api/state')).works[0].status,'Pendiente de cierre');await client.call('/api/reviews',{rating:5,text:'Excelente atención en toda la obra'},409);const closure=await admin.call('/api/works/'+work.id+'/closure',{summary:'Trabajo terminado y revisado por AMC',photos:[],idempotencyKey:'stage6-closure'},201);assert.equal((await client.call('/api/state')).works[0].status,'Pendiente de conformidad');await client.call('/api/closures/'+closure.id+'/reply',{status:'Conforme'});assert.equal((await client.call('/api/state')).works[0].status,'Finalizado');
  const review=await client.call('/api/reviews',{rating:5,text:'Excelente atención en toda la obra'},201);assert.equal(review.approved,false);const edited=await client.call('/api/reviews',{rating:4,text:'Excelente atención, reseña actualizada'},200);assert.equal(edited.id,review.id);
  const requestRejected=await client.call('/api/requests',{name:'Cliente Punilla',phone:'3548000000',town:'La Falda',type:'presupuesto',services:['Canillas'],description:'Cambiar una canilla completa',photos:[]},201);const pdf2=await admin.call('/api/upload',{mime:'application/pdf',base64:Buffer.from('%PDF-1.4\nreject').toString('base64')},201);const rejected=await admin.call('/api/quotes',{requestId:requestRejected.id,externalId:'stage6-reject',version:'7'.repeat(64),number:'AMC-S6-R',items:[{description:'Canilla'}],total:100,pdfId:pdf2.id},201);await client.call('/api/quotes/'+rejected.id+'/reply',{status:'Rechazado'});assert.equal((await admin.call('/api/state')).quotes.find(q=>q.id===rejected.id).status,'Rechazado');
  const notTaken=await client.call('/api/requests',{name:'Cliente Punilla',phone:'3548000000',town:'La Falda',type:'presupuesto',services:['Aberturas'],description:'Pintar aberturas exteriores',photos:[]},201);await admin.call('/api/requests/'+notTaken.id+'/status',{status:'No tomada',reason:'Sin disponibilidad',comment:''});assert.equal((await client.call('/api/state')).requests.find(r=>r.id===notTaken.id).status,'No tomada');
 }finally{await new Promise(resolve=>app.server.close(resolve));}
});

test('stage 6 interactive contracts expose deep links, grouped services and preview viewer',()=>{
 const app=readFileSync(new URL('../public/app.js',import.meta.url),'utf8'),bridge=readFileSync(new URL('../public/presupuestos-bridge.js',import.meta.url),'utf8'),viewer=readFileSync(new URL('../public/media-viewer.js',import.meta.url),'utf8'),team=readFileSync(new URL('../public/team-ui.js',import.meta.url),'utf8');
 assert.match(app,/name="services"/);assert.match(app,/serviceCatalog/);assert.match(app,/page\.startsWith\('presupuesto\/'\)/);assert.match(app,/page\.startsWith\('obra\/'\)/);assert.match(app,/api\/notices\/read/);assert.match(bridge,/suggested-rubrics/);assert.match(bridge,/Ver todo el tarifario/);assert.match(bridge,/Mano de obra estimada/);assert.match(viewer,/\^blob:/);assert.match(team,/employee-profile/);assert.match(team,/Jornal acordado para esta obra/);assert.match(bridge,/function suggestedPrice/);assert.ok(Math.abs(400000/(1-.30)-571428.57)<.01);const handler=bridge.slice(bridge.indexOf("teamBox.addEventListener('input'"),bridge.indexOf("teamBox.addEventListener('click'"));assert.doesNotMatch(handler,/renderEstimatedTeam/);assert.match(handler,/renderSuggestedPrice/);
});


