import test from 'node:test';import assert from 'node:assert/strict';import {createApp} from '../server.mjs';
test('employee permissions, assignment isolation, urgent acknowledgement, revocation and private purchases',async()=>{
 const origin='http://localhost:4180',app=createApp({dbPath:':memory:',origin});app.addUser('owner@amc.test','Strong-Owner-2026!','AMC','admin');await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
 const actor=()=>({cookie:'',csrf:'',async call(p,b,status=200){const r=await fetch(base+p,{method:b===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:this.cookie,'X-CSRF-Token':this.csrf},...(b===undefined?{}:{body:JSON.stringify(b)}),redirect:'manual'});const data=(r.headers.get('content-type')||'').includes('json')?await r.json():await r.text();assert.equal(r.status,status,JSON.stringify(data));if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(data.csrf)this.csrf=data.csrf;return data;}});
 try{
 const admin=actor(),a=actor(),b=actor(),e=actor(),e2=actor();await admin.call('/api/login',{email:'owner@amc.test',password:'Strong-Owner-2026!'});await a.call('/api/register',{email:'a@amc.test',password:'Strong-Client-2026!',name:'Ana'});await b.call('/api/register',{email:'b@amc.test',password:'Strong-Client-2026!',name:'Bruno'});
 const account={email:'employee@amc.test',password:'Strong-Employee-2026!',name:'Juan'};await a.call('/api/employees',account,403);const employee=await admin.call('/api/employees',account,201),other=await admin.call('/api/employees',{...account,email:'other@amc.test',name:'Pedro'},201);assert.equal(employee.password,undefined);await e.call('/api/login',account);await e2.call('/api/login',{...account,email:'other@amc.test'});
 const req=await a.call('/api/requests',{name:'Ana',phone:'3515551234',town:'Valle Hermoso',description:'Visita de obra',service:'Pintura',type:'presupuesto'},201);
 for(const endpoint of ['/api/employees','/api/quotes','/api/requests','/api/purchases','/api/posts','/api/admin/requests'])await e.call(endpoint,{},403);await e.call('/presupuestos',undefined,403);
 const assignment={employeeId:employee.id,requestId:req.id,type:'Urgencia',day:'2030-05-01',time:'10:00',address:'Destino de prueba',instructions:'Medir las paredes y avisar qué materiales faltan.',idempotencyKey:'task-key-001'};const t=await admin.call('/api/assignments',assignment,201);assert.equal((await admin.call('/api/assignments',assignment)).id,t.id);const employeeState=await e.call('/api/state');assert.equal(employeeState.assignments.length,1);assert.equal(employeeState.assignments[0].requestId,undefined);assert.equal(employeeState.assignments[0].history,undefined);assert.equal(employeeState.requests.length,0);assert.equal(employeeState.clients.length,0);assert.equal(employeeState.quotes.length,0);assert.equal(employeeState.notices[0].priority,'urgent');assert.equal((await e2.call('/api/state')).assignments.length,0);assert.equal((await a.call('/api/state')).assignments.length,0);
 const photo=await e.call('/api/upload',{mime:'image/jpeg',base64:Buffer.from([255,216,255,224,0,0]).toString('base64')},201);await e2.call('/api/assignments/'+t.id+'/report',{status:'Recibida',idempotencyKey:'report-001'},404);const report={status:'Recibida',text:'Ya vi el destino.',photos:[photo.id],idempotencyKey:'report-001'};await e.call('/api/assignments/'+t.id+'/report',report,201);await e.call('/api/assignments/'+t.id+'/report',report);assert.ok((await e.call('/api/state')).assignments[0].acknowledgedAt);await admin.call(photo.url);await a.call(photo.url,undefined,404);
 await admin.call('/api/assignments/'+t.id+'/edit',{...assignment,employeeId:other.id});assert.equal((await e.call('/api/state')).assignments.length,0);const reassigned=(await e2.call('/api/state')).assignments[0];assert.equal(reassigned.reports.length,0);assert.equal(reassigned.history,undefined);await e2.call(photo.url,undefined,404);await e.call('/api/assignments/'+t.id+'/report',{...report,idempotencyKey:'report-002'},404);
 await admin.call('/api/employees/'+other.id+'/access',{active:false});assert.equal((await e2.call('/api/state')).user,null);await e2.call('/api/login',{...account,email:'other@amc.test'},401);await admin.call('/api/assignments',{...assignment,employeeId:other.id,idempotencyKey:'task-key-002'},400);await admin.call('/api/employees/'+other.id+'/access',{active:true});assert.equal((await e2.call('/api/state')).user,null);await e2.call('/api/login',{...account,email:'other@amc.test'});await admin.call('/api/employees/'+other.id+'/password',{password:'New-Employee-2026!'});assert.equal((await e2.call('/api/state')).user,null);await e2.call('/api/login',{...account,email:'other@amc.test'},401);await e2.call('/api/login',{email:'other@amc.test',password:'New-Employee-2026!'});
 const invoice=await admin.call('/api/upload',{mime:'application/pdf',base64:Buffer.from('%PDF-1.4\ninvoice').toString('base64')},201);const payload={requestId:req.id,day:'2026-01-01',vendor:'Corralón de prueba',reference:'F-001',amount:50000,detail:'10 bolsas de cemento para la obra.',fileId:invoice.id,idempotencyKey:'purchase-001'};const purchase=await admin.call('/api/purchases',payload,201);await admin.call('/api/purchases',payload);assert.equal((await a.call('/api/state')).purchases.length,0);await a.call(invoice.url,undefined,404);await e2.call(invoice.url,undefined,404);await a.call('/api/purchases/'+purchase.id+'/send',{},403);const oldCount=(await a.call('/api/state')).notices.length;await admin.call('/api/purchases/'+purchase.id+'/send',{});await admin.call('/api/purchases/'+purchase.id+'/send',{});const shared=await a.call('/api/state');assert.equal(shared.purchases.length,1);assert.equal(shared.notices.length,oldCount+1);assert.equal(shared.works.length,0);await a.call(invoice.url);await b.call(invoice.url,undefined,404);assert.equal((await b.call('/api/state')).purchases.length,0);assert.equal((await e2.call('/api/state')).purchases.length,0);

 const ownerState=await admin.call('/api/state');
 await admin.call('/api/employees/'+ownerState.user.id+'/role',{role:'employee'},400);
 await admin.call('/api/employees/'+ownerState.user.id+'/access',{active:false},400);
 await a.call('/api/employees/'+employee.id+'/role',{role:'admin'},403);
 await admin.call('/api/employees/'+employee.id+'/role',{role:'admin'});
 assert.equal((await e.call('/api/state')).user,null);
 await e.call('/api/login',account);assert.equal((await e.call('/api/state')).user.role,'admin');
 await admin.call('/api/employees/'+employee.id+'/role',{role:'employee'});
 assert.equal((await e.call('/api/state')).user,null);
 const sheet=await admin.call('/api/assignments/'+req.id+'/visit-sheet',{idempotencyKey:'admin-sheet-001',day:'2026-01-01',scope:'Pintura interior',measurements:'20 m2',materials:'Pintura',access:'Por la mañana',photos:[]},201);
 assert.ok((await admin.call('/api/state')).visitSheets.some(x=>x.id===sheet.id));
 assert.equal((await a.call('/api/state')).visitSheets.length,0);
 }finally{await new Promise(r=>app.server.close(r));}
});

