import test from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from '../server.mjs';
test('unified client workflow: private messages, visits, quote views, extras and verified receipts',async()=>{
 const origin='http://localhost:4180',app=createApp({dbPath:':memory:',origin});app.addUser('owner@amc.test','Strong-Owner-2026!','AMC','admin');await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
 const client=()=>({cookie:'',csrf:'',async call(path,body,expected=200){const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:this.cookie,'X-CSRF-Token':this.csrf},...(body===undefined?{}:{body:JSON.stringify(body)}),redirect:'manual'});const value=(r.headers.get('content-type')||'').includes('json')?await r.json():await r.text();assert.equal(r.status,expected,JSON.stringify(value));if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];if(value.csrf)this.csrf=value.csrf;return value;}});
 try{
 const admin=client(),a=client(),b=client();await admin.call('/api/login',{email:'owner@amc.test',password:'Strong-Owner-2026!'});await a.call('/api/register',{email:'ana@amc.test',password:'Strong-Client-2026!',name:'Ana'});await b.call('/api/register',{email:'bruno@amc.test',password:'Strong-Client-2026!',name:'Bruno'});
 const state=()=>a.call('/api/state'),userId=(await state()).user.id;
 const manual={userId,service:'Pintura',description:'Pintura interior',idempotencyKey:'manual-001'};await a.call('/api/admin/requests',manual,403);const req=await admin.call('/api/admin/requests',manual,201);assert.equal((await admin.call('/api/admin/requests',manual)).id,req.id);
 const secret=await admin.call('/api/upload',{mime:'image/jpeg',base64:Buffer.from([255,216,255,224,0,0]).toString('base64')},201);
 const msg={text:'Archivo no autorizado: '+secret.url,photos:[],idempotencyKey:'message-001'};await a.call('/api/requests/'+req.id+'/messages',msg,201);await a.call(secret.url,undefined,404);await a.call('/api/requests/'+req.id+'/messages',msg);await b.call('/api/requests/'+req.id+'/messages',{...msg,idempotencyKey:'message-002'},404);assert.equal((await state()).messages.length,1);assert.equal((await b.call('/api/state')).messages.length,0);
 await admin.call('/api/requests/'+req.id+'/messages',{text:'Foto del proyecto',photos:[secret.id],idempotencyKey:'message-003'},201);await a.call(secret.url);await b.call(secret.url,undefined,404);
 const visit={day:'2030-02-21',time:'10:00',duration:60,address:'Domicilio de prueba'};await a.call('/api/requests/'+req.id+'/appointment',visit,403);await admin.call('/api/requests/'+req.id+'/appointment',{...visit,day:'2030-02-30'},400);const v=await admin.call('/api/requests/'+req.id+'/appointment',visit);const req2=await admin.call('/api/admin/requests',{...manual,idempotencyKey:'manual-002'},201);await admin.call('/api/requests/'+req2.id+'/appointment',visit,409);await a.call('/api/appointments/'+v.id+'/status',{status:'Cambio solicitado',reason:'Por la tarde'});await admin.call('/api/requests/'+req.id+'/appointment',{...visit,time:'15:00'});assert.equal((await state()).appointments[0].history.length,3);
 const pdf=await admin.call('/api/upload',{mime:'application/pdf',base64:Buffer.from('%PDF-1.4\nexample').toString('base64')},201);const q=await admin.call('/api/quotes',{requestId:req.id,externalId:'test-q',version:'a'.repeat(64),number:'AMC-TEST',items:[{description:'Pintura'}],total:1000,pdfId:pdf.id},201);await b.call('/api/quotes/'+q.id+'/view',{},404);await a.call('/api/quotes/'+q.id+'/view',{});const seen=(await state()).quotes[0].seenAt;await a.call('/api/quotes/'+q.id+'/view',{});assert.equal((await state()).quotes[0].seenAt,seen);await a.call('/api/quotes/'+q.id+'/reply',{status:'Aceptado'});const w=(await state()).works[0];
 const extra=await admin.call('/api/works/'+w.id+'/extras',{title:'Cielo raso',description:'Pintura adicional',amount:250,idempotencyKey:'extra-001'},201);assert.equal((await state()).works[0].budget,1000);await b.call('/api/extras/'+extra.id+'/reply',{status:'Aceptado'},404);await a.call('/api/extras/'+extra.id+'/reply',{status:'Aceptado'});await a.call('/api/extras/'+extra.id+'/reply',{status:'Aceptado'});assert.equal((await state()).works[0].budget,1250);await a.call('/api/extras/'+extra.id+'/reply',{status:'Rechazado'},409);
 const receiptFile=await a.call('/api/upload',{mime:'application/pdf',base64:Buffer.from('%PDF-1.4\nreceipt').toString('base64')},201);const receipt=await a.call('/api/works/'+w.id+'/receipts',{amount:300,day:'2026-01-01',reference:'transferencia-001',fileId:receiptFile.id,idempotencyKey:'receipt-001'},201);assert.equal((await state()).works[0].payments.length,0);await a.call('/api/receipts/'+receipt.id+'/review',{status:'Confirmado'},403);await admin.call('/api/receipts/'+receipt.id+'/review',{status:'Confirmado'});await admin.call('/api/receipts/'+receipt.id+'/review',{status:'Confirmado'});assert.equal((await state()).works[0].payments.length,1);assert.equal((await state()).works[0].payments[0].amount,300);await b.call(receiptFile.url,undefined,404);await admin.call('/api/receipts/'+receipt.id+'/review',{status:'Rechazado',reason:'Duplicado'},409);
 }finally{await new Promise(r=>app.server.close(r));}
});
